import type { GameDetail } from "@/types/game";
import { variant, createPaymentGroups } from "./game-detail-helpers";

const BE_THE_KING_SERVER_OPTIONS: string[] = [
  "Europe-S1", "Europe-S2", "Europe-S3", "Europe-S4", "Europe-S5", "Europe-S6", "Europe-S7", "Europe-S8", "Europe-S9", "Europe-S10", "Europe-S11", "Europe-S12",
  "US-S1King", "US-S2Empire", "US-S3Scholar", "US-S4Career", "US-S5Genius", "US-S6Palace", "US-S7Blade", "US-S8Glory", "US-S9Honor", "US-S10Talent",
  "US-S11Skillful", "US-S12Victory", "US-S13Wealthy", "US-S14Overload", "US-S15TheOne", "US-S16Official", "US-S17Pioneer", "US-S18Respected", "US-S19Warrior", "US-S20Fortune",
  "US-S21Luck", "US-S22Power", "US-S23Crown", "US-S24Reputation", "US-S25Rich", "US-S26Flourishing", "US-S27Competent", "US-S28Successful", "US-S29Limelight", "US-S30Pillar",
  "US-S31Changan", "US-S32Galdan", "US-S33Glorious", "US-S34Harmony", "US-S35Supreme", "US-S36Literary", "US-S37Eminence", "US-S38Purity", "US-S39Cultivation", "US-S40Tranquil",
  "US-S41Longevity", "US-S42Elegance", "US-S43Happiness", "US-S44Grace", "US-S45Brilliance", "US-S46Eternity", "US-S47Peking", "US-S48Prosperity", "US-S49Righteous", "US-S50Uncorrupted",
  "US-S51BestWishes", "US-S52Resurrection", "US-S53RoyalThrone", "US-S54RichTalents", "US-S55Fame", "US-S56Luxury", "US-S57Skyrocket", "US-S58SuperMan", "US-S59Dawn", "US-S60Awe-inspiring",
  "US-S61Royalty", "US-S62Gorgeous", "US-S63Authority", "US-S64Timing", "US-S65Kingdom", "US-S66Duty", "US-S67Potential", "US-S68Dynasty", "US-S69Achievement", "US-S70Brilliant",
  "US-S71Wisdom", "US-S72Fire", "US-S73Faith", "US-S74Brave", "US-S75Hero", "US-S76Courage", "US-S77Adventure", "US-S78Imperial", "US-S79Jewel", "US-S80Roc",
  "US-S81Dragon", "US-S82Spark", "US-S83Treasure", "US-S84Winner", "US-S85Eliminate", "US-S86Aura", "US-S87Monarch", "US-S88Highlight", "US-S89Loot", "US-S90Flawless",
  "US-S91Phoenix", "US-S92Peerless", "US-S93Elixir", "US-S94Bunker", "US-S95Jade", "US-S96Morality", "US-S97Cohesion", "US-S98Confidence", "US-S99Speed", "US-S100Explorer",
  "US-S101Rule", "US-S102Force", "US-S103Harvest", "US-S104Future", "US-S105Gifted", "US-S106Noble", "US-S107Justice", "US-S108Charm", "US-S109Morale", "US-S110Ambition",
  "US-S111Key", "US-S112Tactic", "US-S113Peace", "US-S114Composure", "US-S115Passion", "US-S116Adour", "US-S117Principle", "US-S118Spring", "US-S119Might", "US-S120Union",
  "US-S121Tranquility", "US-S122Serenity", "US-S123Summer", "US-S124Stardust", "US-S125Governance", "US-S126Billows", "US-S127Clouds", "US-S128Gratitude", "US-S129Precious", "US-S130Flower",
  "US-S131Willow", "US-S132Pride", "US-S133Ultimate", "US-S134Concord", "US-S135Serene", "US-S136Sense", "US-S137Perception", "US-S138Insight", "US-S139Outlook", "US-S140Muse",
  "US-S141Inspiration", "US-S142Alter", "US-S143Revolution", "US-S144Evolution", "US-S145Flame", "US-S146Shine", "US-S147Ray", "US-S148Virtue", "US-S149Terminate", "US-S150Counterattack",
  "US-S151Endless", "US-S152Struggle", "US-S153Against", "US-S154Thrive", "US-S155Ock", "US-S156Cautious", "US-S157Mart", "US-S158Great", "US-S159Respect", "US-S160Leader",
  "US-S161Decisive", "US-S162Unite", "US-S163Praise", "US-S164Elfless", "US-S165Modesty", "US-S166Charitable", "US-S167Dashing", "US-S168Candid", "US-S169Diplomatic", "US-S170Dependable",
  "US-S171Dutiful", "US-S172Learned", "US-S173Motivated", "US-S174Purposeful", "US-S175Reliable", "US-S176Upright", "US-S177Unselfish", "US-S178Tireless", "US-S179Impartial", "US-S180Marvelous",
  "US-S181Judicious", "US-S182Valiant", "US-S183Pushy", "US-S184Stunning", "US-S185Fierce", "US-S186Intelligence",
  "Asia-S1", "Asia-S2", "Asia-S3", "Asia-S4", "Asia-S5", "Asia-S6", "Asia-S7", "Asia-S8", "Asia-S9", "Asia-S10",
  "Asia-S11", "Asia-S12", "Asia-S13", "Bernard_Chong-S14", "Asia-S15", "Asia-S16", "Asia-S17", "Asia-S18", "Asia-S19", "Asia-S20",
  "Asia-S21", "Asia-S22", "Asia-S23", "Asia-S24", "Asia-S25", "Asia-S26", "Asia-S27", "Asia-S28", "Asia-S29", "Asia-S30",
  "Asia-S31", "Asia-S32", "Asia-S33", "Asia-S34", "Asia-S35", "Asia-S36", "Asia-S37", "Asia-S38", "Asia-S39", "Asia-S40",
  "Asia-S41", "Asia-S42", "Asia-S43", "Asia-S44", "Asia-S45", "Asia-S46", "Asia-S47", "Asia-S48", "Asia-S49", "Asia-S50",
  "Asia-S51", "Asia-S52", "Asia-S53", "Asia-S54", "Asia-S55", "Asia-S56", "Asia-S57", "Asia-S58", "Asia-S59", "Asia-S60",
  "Asia-S61", "Asia-S62", "Asia-S63", "Asia-S64", "Asia-S65", "Asia-S66", "Asia-S67", "Asia-S68", "Asia-S69", "Asia-S70",
  "Asia-S71", "Asia-S72", "Asia-S73", "Asia-S74", "Asia-S75", "Asia-S76", "Asia-S77", "Asia-S78", "Asia-S79", "Asia-S80",
  "Asia-S81", "Asia-S82", "Asia-S83", "Asia-S84", "Asia-S85", "Asia-S86", "Asia-S87", "Asia-S88", "Asia-S89", "Asia-S90",
  "Asia-S91", "Asia-S92", "Asia-S93", "Asia-S94", "Asia-S95", "Asia-S96", "Asia-S97", "Asia-S98", "Asia-S99", "Asia-S100",
  "Asia-S101", "Asia-S102", "Asia-S103", "Asia-S104", "Asia-S105", "Asia-S106", "Asia-S107", "Asia-S108", "Asia-S109", "Asia-S110",
  "Asia-S111", "Asia-S112", "Asia-S113", "Asia-S114", "Asia-S115", "Asia-S116", "Asia-S117", "Asia-S118", "Asia-S119", "Asia-S120",
  "Asia-S121", "Asia-S122", "Asia-S123", "Asia-S124", "Asia-S125", "Asia-S126", "Asia-S127", "Asia-S128", "Asia-S129", "Asia-S130",
  "Asia-S131", "Asia-S132", "Asia-S133", "Asia-S134", "Asia-S135", "Asia-S136", "Asia-S137", "Asia-S138", "Asia-S139", "Asia-S140",
  "Asia-S141", "Asia-S142", "Asia-S143", "Asia-S144", "Asia-S145", "Asia-S146", "Asia-S147", "Asia-S148", "Asia-S149", "Asia-S150",
  "Asia-S151", "Asia-S152", "Asia-S153", "Asia-S154", "Asia-S155", "Asia-S156", "Asia-S157", "Asia-S158",
];

const BE_THE_KING: GameDetail = {
  slug: "be-the-king",
  name: "Be The King",
  publisher: "HUANG COOL ENTERTAINMENT",
  image: "/games/be-the-king.webp",
  rating: 5.0,
  ratingCount: "4",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: BE_THE_KING_SERVER_OPTIONS,
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Gold",
      items: [
        variant("60 Gold", 13935, { icon: "/images/btk-gold-icon.webp" }),
        variant("300 Gold", 70811, { icon: "/images/btk-gold-icon.webp" }),
        variant("680 Gold", 141905, { icon: "/images/btk-gold-icon.webp" }),
        variant("2040 Gold", 423723, { icon: "/images/btk-gold-icon.webp" }),
        variant("3400 Gold", 708100, { icon: "/images/btk-gold-icon.webp" }),
        variant("6800 Gold", 1419042, { icon: "/images/btk-gold-icon.webp" }),
      ],
    },
    {
      emoji: "",
      label: "Ult Token",
      items: [
        variant("60 Ult Tokens", 13935, { icon: "/images/btk-ult-token-icon.webp" }),
        variant("300 Ult Tokens", 70811, { icon: "/images/btk-ult-token-icon.webp" }),
        variant("680 Ult Tokens", 141905, { icon: "/images/btk-ult-token-icon.webp" }),
        variant("2040 Ult Tokens", 423723, { icon: "/images/btk-ult-token-icon.webp" }),
        variant("3400 Ult Tokens", 708100, { icon: "/images/btk-ult-token-icon.webp" }),
        variant("6800 Ult Tokens", 1419042, { icon: "/images/btk-ult-token-icon.webp" }),
        variant("20400 Ult Tokens", 4237215, { icon: "/images/btk-ult-token-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Be The King",
  descriptionIntro: "Top up gold dan ult tokens Be The King harga paling murah. Cara topup Be The King termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Gold / Ult tokens otomatis masuk ke akun game",
  ],
};

const BLEACH_MOBILE_3D_SERVER_OPTIONS: string[] = [
  "BLEACH S1", "BLEACH S2", "BLEACH S3", "BLEACH S4", "BLEACH S5", "BLEACH S6", "BLEACH S7", "BLEACH S8", "BLEACH S9", "BLEACH S10",
  "BLEACH S11", "BLEACH S12", "BLEACH S13", "BLEACH S14", "BLEACH S15", "BLEACH S16", "BLEACH S17", "BLEACH S18", "BLEACH S19", "BLEACH S20",
  "BLEACH S21", "BLEACH S22", "BLEACH S23", "BLEACH S24", "BLEACH S25", "BLEACH S26", "BLEACH S27", "BLEACH S28", "BLEACH S29", "BLEACH S30",
  "BLEACH S31", "BLEACH S32", "BLEACH S33", "BLEACH S34", "BLEACH S35", "BLEACH S36", "BLEACH S37", "BLEACH S38", "BLEACH S39", "BLEACH S40",
  "BLEACH S41", "BLEACH S42", "BLEACH S43", "BLEACH S44", "BLEACH S45", "BLEACH S46", "BLEACH S47", "BLEACH S48", "BLEACH S49", "BLEACH S50",
  "BLEACH S51", "BLEACH S52", "BLEACH S53", "BLEACH S54", "BLEACH S55", "BLEACH S56", "BLEACH S57", "BLEACH S58", "BLEACH S59", "BLEACH S60",
  "BLEACH S61", "BLEACH S62", "BLEACH S63", "BLEACH S64", "BLEACH S65", "BLEACH S66", "BLEACH S67", "BLEACH S68", "BLEACH S69", "BLEACH S70",
  "BLEACH S71", "BLEACH S72", "BLEACH S73", "BLEACH S74", "BLEACH S75", "BLEACH S76", "BLEACH S77", "BLEACH S78", "BLEACH S79", "BLEACH S80",
  "BLEACH S81", "BLEACH S82", "BLEACH S83", "BLEACH S84", "BLEACH S85", "BLEACH S86", "BLEACH S87", "BLEACH S88", "BLEACH S89", "BLEACH S90",
  "BLEACH S91", "BLEACH S92", "BLEACH S93", "BLEACH S94", "BLEACH S95", "BLEACH S96", "BLEACH S97", "BLEACH S98", "BLEACH S99", "BLEACH S100",
  "BLEACH S101", "BLEACH S102", "BLEACH S103", "BLEACH S104", "BLEACH S105", "BLEACH S106", "BLEACH S107", "BLEACH S108", "BLEACH S109", "BLEACH S110",
  "BLEACH S111", "BLEACH S112", "BLEACH S113", "BLEACH S114", "BLEACH S115", "BLEACH S116", "BLEACH S117", "BLEACH S118", "BLEACH S119", "BLEACH S120",
  "BLEACH S121", "BLEACH S122", "BLEACH S123", "BLEACH S124", "BLEACH S125",
  "BLEACH TH 1", "BLEACH TH 2", "BLEACH TH 3", "BLEACH TH 4", "BLEACH TH 5", "BLEACH TH 6", "BLEACH TH 7", "BLEACH TH 8", "BLEACH TH 9", "BLEACH TH 10",
  "BLEACH TH 11", "BLEACH TH 12", "BLEACH TH 13", "BLEACH TH 14", "BLEACH TH 15", "BLEACH TH 16", "BLEACH TH 17", "BLEACH TH 18", "BLEACH TH 19", "BLEACH TH 20",
  "BLEACH TH 21", "BLEACH TH 22", "BLEACH TH 23", "BLEACH TH 24", "BLEACH TH 25", "BLEACH TH 26", "BLEACH TH 27", "BLEACH TH 28", "BLEACH TH 29", "BLEACH TH 30",
  "BLEACH TH 31", "BLEACH TH 32", "BLEACH TH 33", "BLEACH TH 34", "BLEACH TH 35", "BLEACH TH 36", "BLEACH TH 37", "BLEACH TH 38", "BLEACH TH 39", "BLEACH TH 40",
  "BLEACH TH 41", "BLEACH TH 42", "BLEACH TH 43", "BLEACH TH 44", "BLEACH TH 45", "BLEACH TH 46", "BLEACH TH 47", "BLEACH TH 48", "BLEACH TH 49", "BLEACH TH 50",
  "BLEACH TH 51", "BLEACH TH 52", "BLEACH TH 53", "BLEACH TH 54", "BLEACH TH 55", "BLEACH TH 56", "BLEACH TH 57", "BLEACH TH 58", "BLEACH TH 59", "BLEACH TH 60",
  "BLEACH TH 61", "BLEACH TH 62", "BLEACH TH 63", "BLEACH TH 64", "BLEACH TH 65", "BLEACH TH 66", "BLEACH TH 67", "BLEACH TH 68", "BLEACH TH 69", "BLEACH TH 70",
  "BLEACH PH 1", "BLEACH PH 2", "BLEACH PH 3", "BLEACH PH 4", "BLEACH PH 5", "BLEACH PH 6", "BLEACH PH 7", "BLEACH PH 8", "BLEACH PH 9", "BLEACH PH 10",
  "BLEACH PH1~3", "BLEACH PH4~10", "BLEACH PH S1~S10",
  "BLEACH ID 1", "BLEACH ID 2", "BLEACH ID 3", "BLEACH ID 4", "BLEACH ID 5", "BLEACH ID 6", "BLEACH ID 7", "BLEACH ID 8", "BLEACH ID 9", "BLEACH ID 10",
  "BLEACH ID 11", "BLEACH ID 12", "BLEACH ID 13", "BLEACH ID 14", "BLEACH ID 15", "BLEACH ID 16", "BLEACH ID 17", "BLEACH ID 18", "BLEACH ID 19",
  "BLEACH ID 1~4", "BLEACH ID 5~8", "BLEACH ID 9~13", "BLEACH ID 14~16", "BLEACH ID 17~19", "BLEACH ID S1~S8",
  "BLEACH M1", "BLEACH M2", "BLEACH M3", "BLEACH M4", "BLEACH M5", "BLEACH M6", "BLEACH M7", "BLEACH M8", "BLEACH M9", "BLEACH M10",
  "BLEACH M11", "BLEACH M12", "BLEACH M1~4", "BLEACH M5~8", "BLEACH M9~12", "BLEACH M S1~S8",
  "BLEACH VN 1", "BLEACH VN 2", "BLEACH VN 3", "BLEACH VN 4", "BLEACH VN 5", "BLEACH VN 6", "BLEACH VN1~6",
  "BLEACH SEA S1~S4", "BLEACH SEA S5~S8", "BLEACH SEA S9~S12", "BLEACH SEA S13~S16", "BLEACH SEA S17~S20", "BLEACH SEA S21~S24", "BLEACH SEA S25~S28", "BLEACH SEA S29~S32", "BLEACH SEA S33~S36", "BLEACH SEA S37~S40",
  "BLEACH SEA S41~S44", "BLEACH SEA S45~S48", "BLEACH SEA S49~S52", "BLEACH SEA S53~S56", "BLEACH SEA S57~S60", "BLEACH SEA S61~S64", "BLEACH SEA S65~S68", "BLEACH SEA S69~S72", "BLEACH SEA S73~S79", "BLEACH SEA S80~S86",
  "BLEACH SEA S87~S93", "BLEACH SEA S94~S100", "BLEACH SEA S101~S107", "BLEACH SEA S1~S20", "BLEACH SEA S21~S48", "BLEACH SEA S49~72", "BLEACH SEA S108~113", "BLEACH SEA S114~119",
  "BLEACH TH S1~S4", "BLEACH TH S5~S8", "BLEACH TH S9~S12", "BLEACH TH S13~S16", "BLEACH TH S17~S20", "BLEACH TH S21~S24", "BLEACH TH S25~S31", "BLEACH TH S32~S38", "BLEACH TH S39~S45", "BLEACH TH S46~S52",
  "BLEACH TH S1~S8", "BLEACH TH S9~S20", "BLEACH TH S21~S38", "BLEACH TH S53~58", "BLEACH TH S59~64",
];

const BLEACH_MOBILE_3D: GameDetail = {
  slug: "bleach-mobile-3d",
  name: "BLEACH Mobile 3D",
  publisher: "Koram",
  image: "/games/bleach-mobile-3d.webp",
  rating: 5.0,
  ratingCount: "4",
  usernameLabel: "Username",
  usernameTooltip:
    "Untuk menemukan ID Pengguna Anda, akses menu 'User Center' di layar mulai, atau Nama Pengguna Anda di layar",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: BLEACH_MOBILE_3D_SERVER_OPTIONS,
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("120 Crystal", 21614, { icon: null }),
        variant("180 Crystal", 32705, { icon: null }),
        variant("300 Crystal", 54033, { icon: null }),
        variant("360 Crystal", 65408, { icon: null }),
        variant("450 Crystal", 81048, { icon: null }),
        variant("600 Crystal", 108064, { icon: null }),
        variant("900 Crystal", 162096, { icon: null }),
        variant("1530 Crystal", 274425, { icon: null }),
        variant("1980 Crystal", 354050, { icon: null }),
        variant("2970 Crystal", 531786, { icon: null }),
        variant("3000 Crystal", 540316, { icon: null }),
        variant("4950 Crystal", 885835, { icon: null }),
        variant("9000 Crystal", 1609573, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi BLEACH Mobile 3D",
  descriptionIntro: "Top up crystal BLEACH Mobile 3D harga paling murah. Cara topup BLEACH Mobile 3D termurah :",
  descriptionSteps: [
    "Masukkan ID & server",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Crystal otomatis masuk ke akun game",
  ],
};

const BLOOD_STRIKE: GameDetail = {
  slug: "blood-strike",
  name: "Blood Strike",
  publisher: "Wizard Games Global Limited",
  image: "/games/blood-strike.webp",
  rating: 4.99,
  ratingCount: "4.39rb",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Special Items",
      items: [
        variant("Level Up Pass", 31320, { icon: null }),
        variant("Strike Pass Elite", 62874, { icon: null }),
        variant("Strike Pass Elite +", 138089, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("100 Gold", 13946, { icon: null }),
        variant("300 Gold", 41836, { icon: null }),
        variant("500 Gold", 69725, { icon: null }),
        variant("1000 Gold", 139449, { icon: null }),
        variant("2000 Gold", 278896, { icon: null }),
        variant("5000 Gold", 697240, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Blood Strike",
  descriptionIntro:
    "Top up Blood Strike harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO. Cara topup Blood Strike via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis diamond masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const CALL_OF_DUTY_MOBILE: GameDetail = {
  slug: "call-of-duty-mobile",
  name: "Call of Duty Mobile",
  publisher: "Garena",
  image: "/games/call-of-duty-mobile.jpg",
  rating: 4.99,
  ratingCount: "5.57rb",
  idLabel: "Open ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Bisa untuk semua akun CODM",
      items: [
        variant("31 CP", 4493, { icon: "/images/codm-cp-icon.webp" }),
        variant("63 CP", 9642, { icon: "/images/codm-cp-icon.webp" }),
        variant("128 CP", 19283, { icon: "/images/codm-cp-icon.webp" }),
        variant("321 CP", 48206, { icon: "/images/codm-cp-icon.webp" }),
        variant("645 CP", 96411, { icon: "/images/codm-cp-icon.webp" }),
        variant("800 CP", 107780, { icon: "/images/codm-cp-icon.webp" }),
        variant("1373 CP", 192820, { icon: "/images/codm-cp-icon.webp" }),
        variant("2060 CP", 289230, { icon: "/images/codm-cp-icon.webp" }),
        variant("2750 CP", 341302, { icon: "/images/codm-cp-icon.webp" }),
        variant("3564 CP", 482049, { icon: "/images/codm-cp-icon.webp" }),
        variant("7656 CP", 964097, { icon: "/images/codm-cp-icon.webp" }),
        variant("15312 CP", 1789704, { icon: "/images/codm-cp-icon.webp" }),
        variant("38280 CP", 4474260, { icon: "/images/codm-cp-icon.webp" }),
        variant("76560 CP", 8948520, { icon: "/images/codm-cp-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Call of Duty Mobile",
  descriptionIntro: "Top up diamond Call of Duty Mobile harga paling murah. Cara topup dm CODM termurah :",
  descriptionSteps: [
    "Masukkan Open ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Cash Point otomatis masuk ke akun game",
  ],
};

const CLOUD_SONG: GameDetail = {
  slug: "cloud-song-saga-of-skywalkers",
  name: "Cloud Song : Saga of Skywalkers",
  publisher: "VNG Singapore",
  image: "/games/cloud-song-saga-of-skywalkers.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "Role ID",
  idTooltip: "Anda dapat menemukan roleId Anda di situs web resmi CloudSong. Contoh: 123_zxshark_1",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("16.000 Ticket", 10909, { icon: null }),
        variant("35.000 Ticket", 17454, { icon: null }),
        variant("49.000 Ticket", 28800, { icon: null }),
        variant("99.000 Ticket", 56725, { icon: null }),
        variant("199.000 Ticket", 109085, { icon: null }),
        variant("359.000 Ticket", 218170, { icon: null }),
        variant("479.000 Ticket", 283620, { icon: null }),
        variant("999.000 Ticket", 567240, { icon: null }),
        variant("1.299.000 Ticket", 839154, { icon: null }),
        variant("1.599.000 Ticket", 1090846, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Cloud Song : Saga of Skywalkers",
  descriptionIntro:
    "Top up ticket Cloud Song : Saga of Skywalkers harga paling murah. Cara topup Cloud Song : Saga of Skywalkers termurah :",
  descriptionSteps: [
    "Masukkan Role ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Ticket otomatis masuk ke akun game",
  ],
};

const CONQUER_ONLINE_SERVER_OPTIONS: string[] = [
  "Wild Kingdom - Dragon", "Wild Kingdom - Phoenix/StatueOfZeus", "Wild Kingdom - Kylin/Tiger", "Wild Kingdom - Lion", "Wild Kingdom - Eagle/Basilisk/Pegasus/Medusa",
  "Gem World - Crystal/Dream", "Gem World - Emerald/Sapphire/Ruby", "Gem World - Turquoise/Diamond/Legends/Reminiscence/Hercules/KingdomWar/AuroraLotus/Dragonfang/NewSoul/Sovereign",
  "Dreams - Triumph", "Dreams - Honor/Justice", "Dreams - Freedom", "Dreams - Faith", "Dreams - Eternity/Uranus",
  "Nature - Volcano/Glory/Pharos/TempleArtemis", "Nature - Thunder/Meteor", "Nature - Lightning", "Nature - Sunshine", "Nature - Snowfall",
  "Galaxy - Venus/Mars/Perfection/ManiacDance/RageOfWar/SkyFlame/ScarOfEarth/Windwalker/JusticeChant", "Galaxy - Mercury/Saturn", "Galaxy - Neptune/Pluto/Jupiter",
  "Wonders - HangingGardens/BabyIcey", "Wonders - Mausoleum/GreatWall/ColossusRhodes", "Wonders - Pyramid",
  "Celebrities - Hebby/KingJus/Nanya", "Celebrities - Columbus",
  "Constellations - Aquarius/Aries/Leo/Pisces", "Constellations - Cancer/Sagittarius/Taurus", "Constellations - Virgo/Gemini", "Constellations - Libra/Capricorn/Fury/Ryee", "Constellations - Scorpio",
  "FairyTales - SnowWhite/Cinderella", "FairyTales - WildSwan/FrogPrince/Bluebird/BeautyandBeast",
  "Myths - Titan/Unicorn",
  "Elements - Dark", "Elements - Light/Conquer13_EU/Backfire_EU/WaveOfBlood_EU/ShadowChaser_EU", "Elements - Fire/Water/Tortuga_EU/jiang_hu", "Elements - Storm/Pishu_EU",
  "Classic - Liberty_O/Prosperity", "Classic - Royalty_EU_O",
  "Celebrations - Lucky7/Evolution/GardenOfEden/TangDynasty/JollyRoger/RisingS/MythicalRunes/LandOfWar/LasVegas",
  "CelebrationsII - Champions_EU/Reunion_EU/BladeTempest_EU/FlameLotus_EU/TempestWings_EU/Anima_EU/JudgeSword_EU/NewChallenge_EU/BloomOfDeath_EU/Tenshi_EU/KnightSpirit_EU",
  "CelebrationsII - DragonWar_EU/ShadowClone_EU/Emperor_EU/EveOfWar_EU",
  "BattleArts - FastBlade",
  "Endeavor - NinjasAssemble/CelestialIsle", "Endeavor - NirvanaWarrior/Gamer/Prologue/CrescentShadow",
  "Global - Glory_EU",
  "Next Episode - Euphoria_EU", "Next Episode - Chimera/Vault_EU", "Next Episode - NewStart_EU/HoverFeather_EU", "Next Episode - Mythforging", "Next Episode - WorldPeace_EU",
  "Next Episode - SkyVeil/WaveChaser", "Next Episode - LavaSea", "Next Episode - BeastFlute_EU", "Next Episode - VassalsRise",
  "Awakening Age - DragonAscension", "Awakening Age - Conquer20",
];

const CONQUER_ONLINE: GameDetail = {
  slug: "conquer-online",
  name: "Conquer Online",
  publisher: "NETDRAGON WEBSOFT (HONG KONG) LIMITED",
  image: "/games/conquer-online.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idTooltip: "Silakan isi nama akun yang Anda gunakan untuk mendaftar Conquer online.",
  serverLabel: "Server",
  serverOptions: CONQUER_ONLINE_SERVER_OPTIONS,
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("60 Conquer Points", 19907, { icon: null }),
        variant("125 Conquer Points", 39814, { icon: null }),
        variant("320 Conquer Points", 98964, { icon: null }),
        variant("530 Conquer Points", 158398, { icon: null }),
        variant("1075 Conquer Points", 316512, { icon: null }),
        variant("2050 Conquer Points", 593496, { icon: null }),
        variant("4200 Conquer Points", 1186705, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Conquer Online",
  descriptionIntro: "Top Up Conquer Points Conquer Online harga paling murah. Cara topup Conqueror Online termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Conquer Points masuk otomatis ke akun Anda.",
  ],
};

const DARK_CONTINENT_MIST_SERVER_OPTIONS: string[] = [
  "Dark", "Continent", "Mist", "Dievs", "ready", "Perendi", "Seul", "Menot", "Hausos", "Dyeus",
  "Jupiter", "Juno", "Astraea", "Agni", "Sculptor", "Mensa", "Narada", "Grus", "Galatea", "Ceres",
  "Triton", "Amalthea", "Vulcan", "Themis", "Nysa", "Proteus", "Pallas", "Eos", "Deimos", "Caelum",
  "Atlas", "Arche", "Muscida", "Alkes", "Nova", "Aurora", "Celeste", "Elektra", "Phobos", "Metis",
  "Atlas", "Arche", "Circe", "Alkes", "Nova", "Aurora", "Celeste", "Elektra", "Hyperion", "Parumleo",
  "Uluka", "Wezen", "Columba", "Spica", "Pavo", "Vela", "Fomalhaut", "Giausar", "Austrinus", "Tucana",
  "Cursa", "Diadem", "Fornax", "Venatici", "Puppis", "Crux", "Eridanus", "Lynx", "Albireo", "Carinae",
  "Canopus", "Antares", "Pleiades", "Vega", "Rigel", "Norum", "Chemica", "Fornacis", "Phaeton", "Chiron",
  "Euryale", "Asclepius", "Muscae", "Therium", "Bestia", "Leporis", "Hevelius", "Lacerta", "Plancius", "Indus",
  "Sextans", "Uraniae", "Scuti", "Habrecht", "Rombus", "Pyxis", "Chevalet", "Pictoris", "Phoenicis", "Siap",
  "Scheat", "Revati", "Situla", "Skat", "Torcular", "Prior", "Veritate", "Talitha", "Saclateni", "Meleph",
  "Regulus", "Pleione", "Mirach", "Maia", "Intercrus", "Jabbah", "Kraz", "Felis", "Beta", "Alpha",
  "Uranus", "Selene", "Nephele", "Iris", "Hemera", "Helios", "Aether", "Sowilo", "Nott", "Teiwaz",
  "Ganesha", "Shiva", "Vishnu", "Brahma", "Hoenir", "Aesir", "Garm", "Surt", "Hati", "Furies",
  "Scheat", "Revati", "Situla", "Hecate", "Torcular", "Prior", "Veritate", "Freya", "Orion", "Dagr",
  "Sulis", "Nuada", "Latobius", "Vejopatis", "Sif", "Ullr", "Nerthus", "Vali", "Gjallarhorn", "Forseti",
  "Bragi", "Idun", "Borr", "Jotunheimen", "Yggdrasil", "Ratatoskr", "Fossegrim", "Midgard", "Muninn", "Sigbin",
  "Barghest", "Salawa", "Hippogriff", "Gamayun", "Tengu", "Strix", "Sirin", "Chamrosh", "Simurgh", "Tetrads",
  "Shezmu", "Reshep", "Tatenen", "Serqet", "Iamus", "Hyacinthus", "Evadne", "Geryon", "Eryx", "Endymion",
  "Deucalion", "Danae", "Cyrene", "Cecrops", "Eligor", "Goemon", "Kali", "Dakini", "Hariti", "Lamia",
  "Asherah", "Ashtoreth", "Skadi", "Cybele",
];

const DARK_CONTINENT_MIST: GameDetail = {
  slug: "dark-continent-mist",
  name: "Dark Continent Mist",
  publisher: "Eyougame",
  image: "/games/dark-continent-mist.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  usernameLabel: "Username",
  usernamePosition: "after",
  serverLabel: "Server",
  serverOptions: DARK_CONTINENT_MIST_SERVER_OPTIONS,
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("900 (600+300) Diamond", 17942, { icon: null }),
        variant("4500 (3000+1500) Diamond", 88584, { icon: null }),
        variant("14500 (9800+4700) Diamond", 279204, { icon: null }),
        variant("28000 (19800+8200) Diamond", 537104, { icon: null }),
        variant("78000 (48800+29200) Diamond", 1400504, { icon: null }),
        variant("98000 (64800+33200) Diamond", 1792960, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Dark Continent Mist",
  descriptionIntro: "Top up Dark Continent : Mist harga paling murah. Cara topup Dark Continent : Mist termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Diamond otomatis masuk ke akun game",
  ],
};

const DAYBREAK_LEGENDS: GameDetail = {
  slug: "daybreak-legends",
  name: "Daybreak Legends",
  publisher: "Linekong Holdings Limited",
  image: "/games/daybreak-legends.jpeg",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  serverLabel: "Server",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("60 Diamonds", 11614, { icon: null }),
        variant("120 Diamonds", 23524, { icon: null }),
        variant("180 Diamonds", 38412, { icon: null }),
        variant("240 Diamonds", 50322, { icon: null }),
        variant("300 Diamonds", 59254, { icon: null }),
        variant("360 Diamonds", 74142, { icon: null }),
        variant("480 Diamonds", 103918, { icon: null }),
        variant("900 Diamonds", 178356, { icon: null }),
        variant("1200 Diamonds", 237907, { icon: null }),
        variant("1800 Diamonds", 386784, { icon: null }),
        variant("3000 Diamonds", 595212, { icon: null }),
        variant("6000 Diamonds", 1190720, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Daybreak Legends",
  descriptionIntro:
    "Top up diamond Daybreak Legends harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO. Cara topup Daybreak Legends via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis diamond masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const DRAGON_RAJA: GameDetail = {
  slug: "dragon-raja",
  name: "Dragon Raja",
  publisher: "Zloong",
  image: "/games/dragon-raja.webp",
  rating: 5.0,
  ratingCount: "28",
  idLabel: "ID",
  idTooltip: "Untuk menemukan ID Pengguna Anda, Ketuk avatar Anda di pojok kiri atas",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Special Items",
      items: [
        variant("Investment Fund 1", 225620, { icon: null }),
        variant("Investment Fund 2", 331932, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("76 Coupons", 23163, { icon: null }),
        variant("456 Coupons", 126975, { icon: null }),
        variant("820 Coupons", 211791, { icon: null }),
        variant("1699 Coupons", 420714, { icon: null }),
        variant("5161 Coupons", 1270403, { icon: null }),
        variant("9056 Coupons", 2117228, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Dragon Raja",
  descriptionIntro: "Top Up Coupon Dragon Raja harga paling murah. Cara topup coupon Dragon Raja termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Metode Pembayaran",
    "Klik Beli Sekarang & lakukan Pembayaran",
    "Coupons masuk otomatis ke akun Anda.",
  ],
};

const DUNK_CITY_DYNASTY: GameDetail = {
  slug: "dunk-city-dynasty",
  name: "Dunk City Dynasty",
  publisher: "Netease",
  image: "/games/dunk-city-dynasty.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idTooltip:
    'Untuk menemukan ID pengguna Anda, masuk ke akun Anda di aplikasi Anda. Klik tombol "Avatar" di sudut kiri atas',
  serverLabel: "Server",
  serverOptions: ["Rucker"],
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("60 Tokens", 13698, { icon: null }),
        variant("300 + 30 Tokens", 78955, { icon: null }),
        variant("980 + 130 Tokens", 223587, { icon: null }),
        variant("1980 + 300 Tokens", 474800, { icon: null }),
        variant("3280 + 600 Tokens", 791598, { icon: null }),
        variant("6480 + 1630 Tokens", 1396164, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Dunk City Dynasty",
  descriptionIntro: "Top up token Dunk City Dynasty harga paling murah. Cara topup Dunk City Dynasty termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Tokens otomatis masuk ke akun game",
  ],
};

const ECHOCALYPSE_SERVER_OPTIONS: string[] = [
  "SEA-Pioneer1", "SEA-Pioneer2", "SEA-Pioneer3", "SEA-Pioneer4", "SEA-Pioneer5", "SEA-Pioneer6", "SEA-Pioneer7", "SEA-Pioneer8", "SEA-Pioneer9", "SEA-Pioneer10",
  "SEA-Empire", "SEA-Bifrost", "SEA-Eastrise", "SEA-Nebu", "SEA-Icefield Howl", "SEA-Teslovik", "SEA-Nova", "SEA-Dark Road", "SEA-Kish", "SEA-Rasparta",
  "SEA-God Eaters", "SEA-Noble Blood", "SEA-Civil Stars", "SEA-Eastrise Royalty", "SEA-Watchtower", "SEA-Luminary Guard", "SEA-Academic Supremacy", "SEA-Royal Supreme", "SEA-Rebel Tribes", "SEA-New Scepter",
  "SEA-Warriors", "SEA-Phantom Thieves", "SEA-Augustine", "SEA-Stoker", "SEA-Mo Capital", "SEA-Memphis", "SEA-Canaan", "SEA-St. Furia", "SEA-Sinai", "SEA-Botley",
  "SEA-Babel Parish", "SEA-Bird Cage Site", "SEA-Trachberg", "SEA-Cold Lake Station", "SEA-Vologda", "SEA-Ominous Ruins", "SEA-Wind Rider Pavilion", "SEA-Stargazing Tower", "SEA-Canhe Slope", "SEA-Cloudferry",
  "SEA-State of Peace", "SEA-Drinking Dragon Bay", "SEA-Leiptorys", "SEA-Heartbreak Ridge", "SEA-Heliapolis", "SEA-Desert Ruins", "SEA-Valley of the Kings", "SEA-Golden Swamp", "SEA-Church of the Testament", "SEA-Kamos",
  "SEA-Sorrow Pass", "SEA-Thousand Ruins Mountain", "SEA-Crystal Factory", "SEA-Sunset Ruins", "SEA-Falaf", "SEA-Siloam", "SEA-Qilin Pass", "SEA-Crystal-sealed Church", "SEA-Rebellious Factory", "SEA-Ankh Glyph",
  "SEA-Leraje Broken Bow", "SEA-Book of Dantalion", "SEA-Crown of Baal", "SEA-Laevatein", "SEA-Futsunomitama", "SEA-Thyrsus", "SEA-Fetters of Fenrir", "SEA-Yata no Kagami", "SEA-Mistilteinn", "SEA-Brionac",
  "SEA-Stone of Destiny", "SEA-Gandiva", "SEA-Holy Grail", "SEA-Sting of Serket", "SEA-Wheel of the Sun Chariot", "SEA-Valiant", "SEA-Pierrot", "SEA-Shelly",
];

const ECHOCALYPSE: GameDetail = {
  slug: "echocalypse",
  name: "Echocalypse",
  publisher: "YOUZU (SINGAPORE) PTE.LTD",
  image: "/games/echocalypse.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idTooltip:
    "Untuk menemukan ID Pengguna Anda, akses http://profile.gtarcade.com/. ID Pengguna Anda akan ditampilkan di tab 'Personal Profile'.",
  serverLabel: "Server",
  serverOptions: ECHOCALYPSE_SERVER_OPTIONS,
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("60 Gold Flower", 13772, { icon: null }),
        variant("300 Gold Flower", 69411, { icon: null }),
        variant("600 Gold Flower", 125051, { icon: null }),
        variant("980 Gold Flower", 208511, { icon: null }),
        variant("1980 Gold Flower", 417161, { icon: null }),
        variant("3280 Gold Flower", 695359, { icon: null }),
        variant("6480 Gold Flower", 1390855, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Echocalypse",
  descriptionIntro: "Top up goldflower Echocalypse harga paling murah. Cara beli goldflower Echocalypse termurah :",
  descriptionSteps: [
    "Masukkan ID dan pilih Server",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Goldflower otomatis masuk ke akun Anda",
  ],
};

export const GAME_DETAILS_2: Record<string, GameDetail> = {
  [BE_THE_KING.slug]: BE_THE_KING,
  [BLEACH_MOBILE_3D.slug]: BLEACH_MOBILE_3D,
  [BLOOD_STRIKE.slug]: BLOOD_STRIKE,
  [CALL_OF_DUTY_MOBILE.slug]: CALL_OF_DUTY_MOBILE,
  [CLOUD_SONG.slug]: CLOUD_SONG,
  [CONQUER_ONLINE.slug]: CONQUER_ONLINE,
  [DARK_CONTINENT_MIST.slug]: DARK_CONTINENT_MIST,
  [DAYBREAK_LEGENDS.slug]: DAYBREAK_LEGENDS,
  [DRAGON_RAJA.slug]: DRAGON_RAJA,
  [DUNK_CITY_DYNASTY.slug]: DUNK_CITY_DYNASTY,
  [ECHOCALYPSE.slug]: ECHOCALYPSE,
};
