import type { GameDetail } from "@/types/game";
import { variant, createPaymentGroups } from "./game-detail-helpers";

const RAGNAROK_ORIGIN: GameDetail = {
  slug: "ragnarok-origin",
  name: "Ragnarok Origin",
  publisher: "Gravity Corporation",
  image: "/games/ragnarok-origin.jpg",
  rating: 5.0,
  ratingCount: "2",
  idLabel: "Secret Code",
  usernameLabel: "Nickname",
  usernamePosition: "after",
  serverLabel: "Server",
  serverOptions: [
    "Prontera-(1~3)/Izlude-9(-10)/Morroc-(1~10)",
    "Prontera-(4~6)/Prontera-10/Izlude-(1~8)",
    "Prontera-(7~9)/Geffen-(1~10)/Payon-(1~10)",
    "Poring Island-(1~10)/Orc Village-(1~10)/Shipwreck-(1~9)/Memoria/Awakening/Ant Hell-(1~10)/Goblin Forest-1(-2-4)/Valentine",
    "Lasagna/1st-Anniversary/Goblin Forest-7/For Honor/Sakura Vows/Goblin Forest-10/Garden-1",
    "1.5th Anniversary/Vicland",
    "2025",
    "Timeless Love",
    "2nd Anniversary",
    "Hugel",
  ],
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("40 Nyan Berry", 13499, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
        variant("125 Nyan Berry", 41395, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
        variant("210 Nyan Berry", 67490, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
        variant("430 Nyan Berry", 135879, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
        variant("900 Nyan Berry", 280755, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
        variant("2300 Nyan Berry", 682991, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
        variant("4800 Nyan Berry", 1366881, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
        variant("9600 Nyan Berry", 2820147, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
        variant("24000 Nyan Berry", 6838001, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
        variant("48000 Nyan Berry", 13676900, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
        variant("96000 Nyan Berry", 27353800, { icon: "/images/ragnarok-origin-nyan-berry-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Ragnarok Origin",
  descriptionIntro: "Top up nyan berry Ragnarok Origin harga paling murah. Cara topup ROO termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Nyan Berry otomatis masuk ke akun game",
  ],
};

const RAGNAROK_X_SERVERS = [
  "Opera Phantom", "Wing of Blessing", "Royal Instrument", "Valhalla", "Gungnir", "Central Plains", "Dark Lord", "Clock Tower", "Comodo", "Rainbow Paradise",
  "Temple of Dawn", "Golden Lava", "Highland", "Demon's Castle", "Sealed Island", "Sipera", "Silent Ship", "Golden Route", "Sapir", "Rose Red",
  "Kingdom of Freedom", "Nicola", "Crystal Waterfall", "Bifrost", "Nastia", "Strouf Treasury", "Green Tranquil Pond", "Ingael", "Dark Priest", "Tome of Glory",
  "Incense Pavilion", "Carew", "Boulders and Horns", "Exquisite Pond", "Nemesis", "Aldebaran", "Honor of Emperium", "Frenetic Land", "Bright Lotus Pond", "Seocho Market",
  "Eudora", "Moonlit Temple", "Hvalueden Wood Ruins", "Dungeon Throne", "Dimension Door", "Gunslinger's Revenge", "Ayothaya", "Luzon", "Majapahit", "Garden City",
  "Manila", "Sukhothai", "Attack On Poring", "Light of Umbala", "Tossakan", "Badang", "Lapulapu", "Gatotkaca", "Srikandi", "Kumpakan",
  "Original Love", "Angeling", "Deviling", "Ghostring", "Mastering", "Drops", "Poporing", "Song Tử", "Xử Nữ", "Bọ Cạp",
  "Nhân Mã", "Thiên Bình", "Sư Tử", "Half Anniversary", "Trail of Illusion", "Angel Spirit", "Wishing Tree", "Infinity Axe", "Meteor Blessing", "Dimension Door",
  "All-Star-Prepare", "Daphne", "Coral Garden", "Mjolnir", "Lightning Cloud", "Ghastly Cemetery", "Hero Association", "Monster Association", "Taekwon", "3rd Anniversary",
  "The Demon Carnival", "Einbroch", "Lost City", "4th Job", "Abyssal Hole", "Ancestral Hall", "Paweena", "Fallen Maple Forest", "Bookshelf Arcade", "Rachel",
  "赛事服", "Hermit Hut", "Gardner", "Glass Brooch", "Jarnvvalue", "Felix", "Giant Claw Throne", "Laevatain", "Ophelia", "Fairy Wing",
  "Night Pearl", "Tracy", "Telekinetic Orb", "Mainz", "Surtr", "Clearwater Pearl", "Mandragora", "Hollgrehenn", "Weinst", "Tyrfing",
  "Ahlspiess", "Black Iron Medal", "Inverse Scale", "Villar", "Divine Shield", "Falken Blitz", "Zimmerman", "Hurricane Fury", "Kronos", "Alson",
  "Tome of Eternity", "Kalasag", "Toad Shadow", "Shadow Guard", "Gemmed Crown", "Balmung", "Sphinx Spirit", "Ring of Thorns", "Luminary", "Runic Factory",
  "Scarlet Phantom", "Poring Crown", "King's Apostle", "Royal Blood", "Royal Road", "Alpha Wolf Gem", "Fullers", "Oxi", "Angel Kiss", "Omniscient Angel",
  "Angel Wing", "Whispering Demon", "Demon Horn", "Mindful Jade", "Festive Lantern", "Blissful Brvaluee", "Crystal Tiara", "Carousel", "Resurrection Night March", "Warm Winter",
  "Royal Chivalry", "Golden Wings", "Gladsheim", "Crystal Ball", "Promise Carriage", "Red Gilded Satin", "Moonlit Cave", "Deep Sea Deity", "Albel", "Pooler Garden",
  "Blake", "Elvira", "Champagne Blue", "Underground Fighting Arena", "Gold Obsvalueian", "Sword of Victory", "Arielle", "Keyte", "Secret Cave", "Soul Obelisk",
  "Brock", "White Muslin Bow Tie", "Fuller", "Lonvius", "Rising Peaks Forest", "Twilight Blade", "The Sword of Giant", "Rainbow Coral", "Hobson", "Njord",
  "tmp2300", "tmp2301", "tmp2302", "tmp2303", "tmp2304", "tmp2305", "tmp2310", "tmp2311", "tmp2312", "tmp2313",
  "tmp2314", "tmp2315", "tmp2320", "tmp2321", "tmp2322", "tmp2323", "tmp2324", "tmp2325", "tmp2330", "tmp2331",
  "tmp2332", "tmp2333", "tmp2334", "tmp2335",
];

const RAGNAROK_X: GameDetail = {
  slug: "ragnarok-x",
  name: "Ragnarok X",
  publisher: "PIPO (HK) Limited",
  image: "/games/ragnarok-x.webp",
  rating: 5.0,
  ratingCount: "28",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: RAGNAROK_X_SERVERS,
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Special Items",
      items: [
        variant("Covenant of Encouragement (Kafra W)", 228953, { icon: "/images/ragnarok-x-kafra-w-icon.webp" }),
        variant("Assurance of Exclusivity (Kafra Telling)", 475568, { icon: "/images/ragnarok-x-kafra-telling-icon.webp" }),
        variant("Oath of Bond (Kafra Clarice)", 632536, { icon: "/images/ragnarok-x-kafra-clarice-icon.webp" }),
      ],
    },
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("2080 Diamonds", 80484, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("2110 Diamonds", 82317, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("2360 Diamonds", 82817, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("4150 Diamonds", 160968, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("4210 Diamonds", 164467, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("4720 Diamonds", 168633, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("6910 Diamonds", 268279, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("9490 Diamonds", 337264, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("10540 Diamonds", 410916, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("14170 Diamonds", 536056, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("19380 Diamonds", 601376, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("21430 Diamonds", 821496, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("32180 Diamonds", 1218747, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("43420 Diamonds", 1607999, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("48700 Diamonds", 1680818, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("53050 Diamonds", 2053740, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("98100 Diamonds", 3007042, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("85370 Diamonds", 3161010, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("106100 Diamonds", 4062823, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("137550 Diamonds", 4708021, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
        variant("172190 Diamonds", 6375341, { icon: "/images/ragnarok-x-diamonds-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Ragnarok X",
  descriptionIntro: "Top up diamonds Ragnarok X harga paling murah. Cara topup Ragnarok X termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Diamonds otomatis masuk ke akun game",
    "**Proses Manual 1-10 Menit",
  ],
};

const REVELATION_INFINITE_JOURNEY: GameDetail = {
  slug: "revelation-infinite-journey",
  name: "Revelation : Infinite Journey",
  publisher: "VNG Corporation",
  image: "/games/revelation-infinite-journey.webp",
  rating: 5.0,
  ratingCount: "22",
  idLabel: "Role ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Special Item",
      items: [
        variant("Newbie Pack", 8727, { icon: null }),
        variant("Monthly Card (7 Days)", 8727, { icon: null }),
        variant("Battle Pass", 56725, { icon: null }),
        variant("Monthly Card", 56725, { icon: null }),
        variant("Growth Fund", 113449, { icon: null }),
        variant("Monthly Card (Premium)", 113449, { icon: null }),
        variant("Battle Pass (Plus)", 113449, { icon: null }),
        variant("Daily Pack (7 Days)", 392705, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("40 + 6 Jade", 8745, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("110 + 17 Jade", 21863, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("230 + 35 Jade", 43725, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("460 + 69 Jade", 87450, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("920 + 138 Jade", 174900, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("1150 + 173 Jade", 218625, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("1380 + 207 Jade", 262350, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("1610 + 242 Jade", 306075, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("2300 + 345 Jade", 437250, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("3220 + 483 Jade", 612150, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("4600 + 690 Jade", 874500, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("9200 + 1380 Jade", 1749000, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
        variant("23000 + 3450 Jade", 4372500, { icon: "/images/revelation-infinite-journey-jade-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Revelation : Infinite Journey",
  descriptionIntro:
    "Top up jade Revelation Mobile : Infinite Journey harga paling murah. Cara topup Revelation Mobile termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Jade otomatis masuk ke akun game",
  ],
};

const SAUSAGE_MAN: GameDetail = {
  slug: "sausage-man",
  name: "Sausage Man",
  publisher: "X.D. Network",
  image: "/games/sausage-man.webp",
  rating: 5.0,
  ratingCount: "162",
  idLabel: "User ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("61 Candies", 14997, { icon: "/images/sausage-man-candies-icon.webp" }),
        variant("186 Candies", 44825, { icon: "/images/sausage-man-candies-icon.webp" }),
        variant("318 Candies", 74985, { icon: "/images/sausage-man-candies-icon.webp" }),
        variant("686 Candies", 150137, { icon: "/images/sausage-man-candies-icon.webp" }),
        variant("1378 Candies", 300605, { icon: "/images/sausage-man-candies-icon.webp" }),
        variant("2118 Candies", 448408, { icon: "/images/sausage-man-candies-icon.webp" }),
        variant("3548 Candies", 749179, { icon: "/images/sausage-man-candies-icon.webp" }),
        variant("7108 Candies", 1501522, { icon: "/images/sausage-man-candies-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Sausage Man",
  descriptionIntro: "Top Up Candy Sausage Man",
  descriptionSteps: [
    "Masukkan User ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Candy masuk otomatis ke akun Anda",
  ],
};

const SCROLL_OF_ONMYOJI_SAKURA_SWORD_SERVERS = [
  "S1-Taman sakura", "S2-Akademi Mitama", "S3-Gunung roh", "S4-Ketiadaan", "S5-Kosong", "S6-Stargate", "S7-Realm Takdir", "S8-Reruntuhan", "S9-Kuil Cahaya", "S10-Pavilion langit",
  "S11-Taman impian", "S12-Hutan diam", "S13-Jalur Langit", "S14-Pencarian Buluh", "S15-Misteri Elf", "S16-Hutan roh iblis", "S17-Laut dalam", "S18-Kuil Beruang", "S19-Domain kegelapan", "S20-Distorsi",
  "S21-Kenshi", "S22-Uzume", "S23-Fujin", "S24-Inari", "S25-Shikoku", "S26-Okami", "S27-Nagi", "S28-Kojiki", "S29-Raijin", "S30-Suijin",
  "S31-Susanoo", "S32-Orochi", "S33-Tenjin", "S34-Otohime", "S35-Ame", "S36-Kaguya", "S37-Hana", "S38-Kojin", "S39-Mikoto", "S40-Jizo",
  "S41-Konoha", "S42-Aizen", "S43-Kannon", "S44-Ebisu", "S45-Danau berkabut", "S46-Gunung monster", "S47-Kota Bulan", "S48-Hutan Ajaib", "S49-Balai Bumi", "S50-Oiwa",
  "S51-Sazae Oni", "S52-Yama Uba", "S53-Hannya", "S54-Namanari", "S55-Ikiryo", "S56-Chunari", "S57-Honnari", "S58-Ubume", "S59-Nure Onna", "S60-Nukekubi",
  "S61-Rokurkubi", "S62-Ubagabi", "S63-Hone Onna", "S64-Akashita", "S65-Kiyohime", "S66-Obake", "S67-Kamaitaichi", "S68-Kekkai", "S69-Isonade", "S70-Masakatsu",
  "S71-Yasumori", "S72-Mototsuna", "S73-Kagemori", "S74-Terukage", "S75-Mitsuhide", "S76-Nobutomo", "S77-Yoshihisa", "S78-Morinari", "S79-Shigetsuna", "S80-Yurei",
  "S81-Aokage", "S82-Muratsugu", "S83-Arima", "S84-Hisamasa", "S85-Nagaharu", "S86-Morichika", "S87-Shigezane", "S88-Masamune", "S89-Toshikatsu", "S90-Fusahide",
  "S91-Ujisato", "S92-Naomasa", "S93-Tsunenaga", "S94-Hattori", "S95-Hideharu", "S96-Kennyo", "S97-Masatoshi", "S98-Tsuneoki", "S99-Isshiki", "S100-Imagawa",
  "S101-Hiroie", "S102-Yukinaga", "S103-Hisamichi", "S104-Matsudaira", "S105-Hatobo", "S106-Nageki", "S107-Kappa", "S108-Ryuo", "S109-Nozuchi", "S110-Yosei",
  "S111-Ushirogami", "S112-Tsurube", "S113-Tsukuyomi", "S114-Momonji", "S115-Suzaku", "S116-Seiryuu", "S117-Byakko", "S118-Genbu", "S119-Shiryo", "S120-Kahaku",
  "S121-Rojinbi", "S122-Onryo", "S123-Kasha", "S124-Tenko", "S125-Nue", "S126-Yuki-Onna", "S127-Mononoke", "S128-Okiku", "S129-Kodama", "S130-Issie",
  "S131-Hakano", "S132-Gyuki", "S133-Funayurei", "S134-Dodomeki", "S135-Kosagi", "S136-Kirin", "S137-Amesu", "S138-Akubozu", "S139-Yuuki", "S140-Supia",
  "S141-Onisuzume", "S142-Nyoromo", "S143-Kishi", "S144-Utsudon", "S145-Nashi", "S146-Myuu", "S147-Kabuto", "S148-Iibui", "S149-Azumao", "S150-Rakki",
  "S151-Ebiwara", "S152-Tama", "S153-Jugon", "S154-Koiru", "S155-Gyaropu", "S156-Uindie", "S157-Soma", "S158-Rokon", "S159-Korata", "S160-Catapi",
  "S161-Suripu", "S162-Hitokage", "S163-Kameru", "S164-Toranseru", "S165-Onidoriru", "S166-Kokun", "S167-Pukuri", "S168-Kyatapi", "S169-Gadi", "S170-Nyomoro",
  "S171-Saihon", "S172-Genga", "S173-Iwaku", "S174-Rujura", "S175-Nyasu", "S176-Hakuryu", "S177-Furiza", "S178-Myutsu", "S179-Odairu", "S180-Otachi",
  "S181-Himanatsu", "S182-Kimawari", "S183-Guraiga", "S184-Nyura", "S185-Daikon", "S186-Kiruria", "S187-Sanaito", "S188-Kingu", "S189-Tsuchinin", "S190-Yajiron",
  "S191-Jiransu", "S192-Todogura", "S193-Hayashi", "S194-Ratiosu", "S195-Hikozaru", "S196-Nyaruma", "S197-Tamanta", "S198-Hyakki", "S199-Ishimai", "S200-Zoroa",
  "S201-Rigure", "S202-Obemu", "S203-Shishiko", "S204-Hitotsuki", "S205-Maika", "S206-Kuzumo", "S207-GIN", "S208-ARNIUS", "S209-DAICHI", "S210-EIJI",
  "S211-HIDEYOSHI", "S212-HARU", "S213-HINOTO", "S214-HADJI", "S215-HIRO", "S216-HIKARU", "S217-ISAMU", "S218-ICHIRO", "S219-KADO", "S220-KAINDRA",
  "S221-KENSHI", "S222-KENICHI", "S223-KO", "S224-KAZUO", "S225-MAMORU", "S226-MASKUR", "S227-MASHASHI", "S228-MASUMI", "S229-MASO", "S230-KOBAYASHI",
  "S231-MIKIO", "S232-MASAYUKI", "S233-MAKOTO", "S234-MORIO", "S235-NANDITO", "S236-NAOKI", "S237-NAOTO", "S238-ICHIMARU", "S239-KAWAGUCHI", "S240-NOBU",
  "S241-NIKY", "S242-OKI", "S243-NORI", "S244-NOBORU", "S245-RAIDEN", "S246-REN", "S247-GYO", "S248-NEN", "S249-TEN", "S250-MASHASHI",
  "S251-KENSHI", "S252-RYOICHI", "S253-REIYU", "S254-RINGO", "S255-ROKA", "S256-RIYO", "S257-RYOTA", "S258-RYU", "S259-RYUZAKI", "S260-SAYKOJI",
  "S261-SUZANO", "S262-SANO", "S263-SABURO", "S264-SEIKO", "S265-SEIYA", "S266-SHIN", "S267-SHIRO", "S268-SHINJI", "S269-SINA", "S270-SORA",
  "S271-SATORU", "S272-SHIMA", "S273-SHOUHEI", "S274-SHUJI", "S275-SHINICHI", "S276-SUNO", "S277-TAMA", "S278-TARO", "S279-TOMI", "S280-TAKAO",
  "S281-TAKASHI", "S282-TAKEDA", "S283-TSUTOMU", "S284-TOSHIO", "S285-TOSHIRO", "S286-YUKI", "S287-YOSHIMITSU", "S288-YASUO", "S289-ZEN", "S290-NEIJI",
  "S291-ICHIGO", "S292-KUROSAWA", "S293-YUUTO", "S294-KINDAICHI", "S295-YASHUHIRO", "S296-YASUO", "S297-AYA", "S298-AYUMI", "S299-CHEIKO", "S300-AYAKO",
  "S301-Cybele", "S302-Skadi", "S303-Ashtoreth", "S304-Asherah", "S305-Lamia", "S306-Hariti", "S307-Dakini", "S308-Kali", "S309-Goemon", "S310-Eligor",
  "S311-Thoth", "S312-Barong", "S313-Rangda", "S314-Strix", "S315-Tengu", "S316-Gamayun", "S317-Hippogriff", "S318-Salawa", "S319-Barghest", "S320-Sigbin",
  "S321-Muninn", "S322-Midgard", "S323-Fossegrim", "S324-Ratatoskr", "S325-Yggdrasil", "S326-Jotunheimen", "S327-Borr", "S328-Idun", "S329-Bragi", "S330-Forseti",
  "S331-Gjallarhorn", "S332-Vali", "S333-Nerthus", "S334-Ullr", "S335-Sif", "S336-Glitnir", "S337-Hermod", "S338-Gefjun", "S339-Fjorgynn", "S340-Sol",
  "S341-Gatotkaca", "S342-Yudhistira", "S343-Bima", "S344-Arjuna", "S345-Nakula", "S346-Sadewa", "S347-Siliwangi", "S348-AnglingDharma", "S349-Purbasari", "S350-JakaTingkir",
  "S351-Abumiguchi", "S352-Chochinbi", "S353-Hakutaku", "S354-Bakeneko", "S355-Jubokko", "S356-Akabeko", "S357-Hyosube", "S358-Ikuchi", "S359-Basan", "S360-Akashita",
  "S361-Daitengu", "S362-Kameosa", "S363-Momonji", "S364-Amamehagi", "S365-Hinode", "S366-Issie", "S367-Kawauso", "S368-Hotoke", "S369-Amanozako", "S370-Kanedama",
  "S371-Harionago", "S372-Keneo", "S373-Bashonosei", "S374-Jatai", "S375-Aosaginohi", "S376-Hannya", "S377-Goryo", "S378-Karura", "S379-Funayurei", "S380-Itsumade",
  "S381-Mikaribaba", "S382-Dodomeki", "S383-Kangiten", "S384-Hitodama", "S385-Jibakurei", "S386-Mizuchi", "S387-Hososhi", "S388-Ikiryo", "S389-Mujina", "S390-Isonade",
  "S391-Furaribi", "S392-Kasha", "S393-Janjanbi", "S394-Enenra", "S395-Hashihime", "S396-Gashadokuro", "S397-Kamikiri", "S398-Fujin", "S399-Gozu", "S400-Mezu",
  "S401-Sirius", "S402-Polaris", "S403-Claia", "S404-Karya", "S405-Ekho", "S406-Balanis", "S407-Midas", "S408-MidasLeda", "S409-Ixion", "S410-Iamus",
  "S411-Evadne", "S412-Geryon", "S413-Eryx", "S414-Apus", "S415-Antlia", "S416-Reticulum", "S417-Octans", "S418-Microscopium", "S419-Telescopium", "S420-Circinus",
  "S421-Norma", "S422-Bootes", "S423-Canes", "S424-Draco", "S425-Ursa Minor", "S426-Ursa Major", "S427-Monoceros", "S428-Lepus", "S429-Canis Major", "S430-Orion",
  "S431-Ara", "S432-Lupus", "S433-Centaurus", "S434-Serpens", "S435-Ophiuchus", "S436-Corvus", "S437-Crater", "S438-Hydra", "S439-Cygnus", "S440-Lyra",
  "S441-Aquila", "S442-Sagitta", "S443-Hercules", "S444-Auriga", "S445-Pegasus", "S446-Cepheus", "S447-Cetus", "S448-Cassiopeia", "S449-Perseus", "S450-Andromeda",
  "S451-Sagittarius", "S452-Scorpio", "S453-Libra", "S454-Virgo", "S455-Leo", "S456-Cancer", "S457-Gemini", "S458-Taurus",
];

const SCROLL_OF_ONMYOJI_SAKURA_SWORD: GameDetail = {
  slug: "scroll-of-onmyoji-sakura-sword",
  name: "Scroll of Onmyoji Sakura Sword",
  publisher: "Eyougame",
  image: "/games/scroll-of-onmyoji-sakura-sword.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: SCROLL_OF_ONMYOJI_SAKURA_SWORD_SERVERS,
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("90 Gioks", 15091, { icon: null }),
        variant("450 Gioks", 75450, { icon: null }),
        variant("900 Gioks", 150900, { icon: null }),
        variant("1350 Gioks", 226350, { icon: null }),
        variant("1840 Gioks", 301798, { icon: null }),
        variant("4800 Gioks", 754496, { icon: null }),
        variant("9800 Gioks", 1508990, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Scroll of Onmyoji Sakura Sword",
  descriptionIntro:
    "Top up gioks Scroll of Onmyoji : Sakura & Sword harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore. Cara topup Scroll of Onmyoji : Sakura & Swordvia ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis gioks masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const SPEED_DRIFTERS: GameDetail = {
  slug: "speed-drifters",
  name: "Speed Drifters",
  publisher: "Garena",
  image: "/games/speed-drifters.webp",
  rating: 5.0,
  ratingCount: "8",
  idLabel: "ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("56 Diamonds", 9429, { icon: null }),
        variant("112 Diamonds", 18857, { icon: null }),
        variant("282 Diamonds", 47141, { icon: null }),
        variant("579 Diamonds", 94280, { icon: null }),
        variant("1230 Diamonds", 188559, { icon: null }),
        variant("1845 Diamonds", 282838, { icon: null }),
        variant("3134 Diamonds", 471396, { icon: null }),
        variant("6279 Diamonds", 942791, { icon: null }),
        variant("31450 Diamonds", 4849551, { icon: null }),
        variant("63000 Diamonds", 9718462, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Speed Drifters",
  descriptionIntro:
    "Top up diamond Speed Drifters harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore. Cara topup Speed Drifters via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis diamond masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const STATE_OF_SURVIVAL_ZOMBIE_WAR: GameDetail = {
  slug: "state-of-survival-zombie-war",
  name: "State of Survival: Zombie War",
  publisher: "FunPlus",
  image: "/games/state-of-survival-zombie-war.webp",
  rating: 5.0,
  ratingCount: "310",
  idLabel: "ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("100 Diamonds", 16779, { icon: null }),
        variant("500 Diamonds", 83892, { icon: null }),
        variant("1.000 Diamonds", 167784, { icon: null }),
        variant("2.000 Diamonds", 335566, { icon: null }),
        variant("5.000 Diamonds", 838912, { icon: null }),
        variant("10.000 Diamonds", 1706261, { icon: null }),
        variant("20.000 Diamonds", 3355647, { icon: null }),
        variant("50.000 Diamonds", 8389116, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi State of Survival: Zombie War",
  descriptionIntro:
    "Top up diamond State of Survival: Zombie War harga paling murah. Cara top up diamond State of Survival termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Diamond otomatis masuk ke akun Anda.",
  ],
};

const STORMSHOT: GameDetail = {
  slug: "stormshot",
  name: "Stormshot",
  publisher: "FunPlus International AG",
  image: "/games/stormshot.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("500 Diamonds", 85029, { icon: null }),
        variant("1000 Diamonds", 170342, { icon: null }),
        variant("2000 Diamonds", 341253, { icon: null }),
        variant("5000 Diamonds", 850288, { icon: null }),
        variant("10000 Diamonds", 1706261, { icon: null }),
        variant("20000 Diamonds", 3412522, { icon: null }),
        variant("50000 Diamonds", 8502867, { icon: null }),
        variant("100000 Diamonds", 17062608, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Stormshot",
  descriptionIntro:
    "Top up Stormshot diamond Stormshot harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore. Cara topup Stormshot via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis diamond masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const SUPER_SUS: GameDetail = {
  slug: "super-sus",
  name: "Super SUS",
  publisher: "PI Productions PTE.LTD",
  image: "/games/super-sus.webp",
  rating: 5.0,
  ratingCount: "618",
  idLabel: "ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Special Items",
      items: [
        variant("Weekly Card", 13086, { icon: null }),
        variant("SUPER PASS BUNDLE", 133124, { icon: null }),
        variant("Monthly Card", 143553, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("100 Goldstar", 13086, { icon: "/images/super-sus-goldstar-icon.webp" }),
        variant("310 Goldstar", 39445, { icon: "/images/super-sus-goldstar-icon.webp" }),
        variant("520 Goldstar", 65803, { icon: "/images/super-sus-goldstar-icon.webp" }),
        variant("SUPER PASS", 65803, { icon: null }),
        variant("1060 Goldstar", 133124, { icon: "/images/super-sus-goldstar-icon.webp" }),
        variant("Super VIP Card", 160241, { icon: null }),
        variant("2180 Goldstar", 273642, { icon: "/images/super-sus-goldstar-icon.webp" }),
        variant("5600 Goldstar", 701833, { icon: "/images/super-sus-goldstar-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Super SUS",
  descriptionIntro: "Top up Golden Star Super SUS harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore.",
  descriptionSteps: [
    "Cara topup :",
    "1) Masukkan Data Akun",
    "2) Pilih Nominal",
    "3) Tentukan Jumlah Pembelian",
    "4) Pilih Pembayaran",
    "5) Masukkan Kode Promo (jika ada)",
    "6) Isi Detail Kontak",
    "7) Klik Pesan Sekarang dan lakukan Pembayaran",
    "8) Selesai",
  ],
};

const TIME_RAIDERS_SERVERS = [
  ...Array.from({ length: 169 }, (_, i) => `SEA-${i + 1}`),
  ...Array.from({ length: 65 }, (_, i) => `EU-${i + 1}`),
  ...Array.from({ length: 76 }, (_, i) => `US-${i + 1}`),
  "TS",
];

const TIME_RAIDERS: GameDetail = {
  slug: "time-raiders",
  name: "Time Raiders",
  publisher: "YOUZU (SINGAPORE) PTE.LTD",
  image: "/games/time-raiders.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: TIME_RAIDERS_SERVERS,
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("600 Blue Diamonds", 16609, { icon: null }),
        variant("3000 Blue Diamonds", 83721, { icon: null }),
        variant("6800 Blue Diamonds", 167613, { icon: null }),
        variant("12800 Blue Diamonds", 335395, { icon: null }),
        variant("32800 Blue Diamonds", 838742, { icon: null }),
        variant("64800 Blue Diamonds", 1677654, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Time Raiders",
  descriptionIntro: "Topup diamonds Time Raiders harga paling murah. Cara beli diamond Time Raiders termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Diamond masuk otomatis ke akun Anda",
  ],
};

const TOM_AND_JERRY_CHASE: GameDetail = {
  slug: "tom-and-jerry-chase",
  name: "Tom and Jerry: Chase",
  publisher: "NetEase",
  image: "/games/tom-and-jerry-chase.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: ["Asia"],
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("60 Diamonds", 15182, { icon: null }),
        variant("180 Diamonds", 44530, { icon: null }),
        variant("300 Diamonds", 73879, { icon: null }),
        variant("600 Diamonds", 150794, { icon: null }),
        variant("1200 Diamonds", 302600, { icon: null }),
        variant("1800 Diamonds", 464525, { icon: null }),
        variant("3000 Diamonds", 799509, { icon: null }),
        variant("6000 Diamonds", 1507933, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Tom and Jerry: Chase",
  descriptionIntro: "Top Up Diamonds Tom and Jerry harga paling murah. Cara topup Tom & Jerry termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Diamonds masuk otomatis ke akun Anda.",
  ],
};

const TOWER_BRAWL: GameDetail = {
  slug: "tower-brawl",
  name: "Tower Brawl",
  publisher: "Youzu (Singapore) Pte. Ltd.",
  image: "/games/tower-brawl.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("80 Diamonds", 19907, { icon: null }),
        variant("500 Diamond", 98964, { icon: null }),
        variant("1200 Diamond", 197927, { icon: null }),
        variant("2500 Diamond", 395569, { icon: null }),
        variant("6500 Diamond", 988779, { icon: null }),
        variant("14000 Diamond", 1977558, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Tower Brawl",
  descriptionIntro: "Top up diamonds Tower Brawl harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore.",
  descriptionSteps: [
    "Cara topup :",
    "1) Masukkan Data Akun",
    "2) Pilih Nominal",
    "3) Tentukan Jumlah Pembelian",
    "4) Pilih Pembayaran",
    "5) Masukkan Kode Promo (jika ada)",
    "6) Isi Detail Kontak",
    "7) Klik Pesan Sekarang dan lakukan Pembayaran",
    "8) Selesai",
  ],
};

const VALORANT: GameDetail = {
  slug: "valorant",
  name: "Valorant",
  publisher: "Riot Games",
  image: "/games/valorant.jpg",
  rating: 5.0,
  ratingCount: "4.50rb",
  idLabel: "Valorant ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Region ID (Indonesia)",
      items: [
        variant("475 Points", 54776, { icon: "/images/valorant-points-icon.webp" }),
        variant("950 Points", 109551, { icon: "/images/valorant-points-icon.webp" }),
        variant("1000 Points", 109551, { icon: "/images/valorant-points-icon.webp" }),
        variant("1475 Points", 164327, { icon: "/images/valorant-points-icon.webp" }),
        variant("2050 Points", 219101, { icon: "/images/valorant-points-icon.webp" }),
        variant("2000 Points", 219102, { icon: "/images/valorant-points-icon.webp" }),
        variant("2525 Points", 273877, { icon: "/images/valorant-points-icon.webp" }),
        variant("3050 Points", 328652, { icon: "/images/valorant-points-icon.webp" }),
        variant("3650 Points", 380492, { icon: "/images/valorant-points-icon.webp" }),
        variant("4125 Points", 435267, { icon: "/images/valorant-points-icon.webp" }),
        variant("4100 Points", 438202, { icon: "/images/valorant-points-icon.webp" }),
        variant("4650 Points", 490043, { icon: "/images/valorant-points-icon.webp" }),
        variant("5350 Points", 546773, { icon: "/images/valorant-points-icon.webp" }),
        variant("5700 Points", 599593, { icon: "/images/valorant-points-icon.webp" }),
        variant("5825 Points", 601548, { icon: "/images/valorant-points-icon.webp" }),
        variant("6350 Points", 656324, { icon: "/images/valorant-points-icon.webp" }),
        variant("7300 Points", 760983, { icon: "/images/valorant-points-icon.webp" }),
        variant("7400 Points", 765874, { icon: "/images/valorant-points-icon.webp" }),
        variant("8400 Points", 875425, { icon: "/images/valorant-points-icon.webp" }),
        variant("9000 Points", 927264, { icon: "/images/valorant-points-icon.webp" }),
        variant("8990 Points", 927264, { icon: "/images/valorant-points-icon.webp" }),
        variant("10000 Points", 1036815, { icon: "/images/valorant-points-icon.webp" }),
        variant("11000 Points", 1074961, { icon: "/images/valorant-points-icon.webp" }),
        variant("10700 Points", 1093545, { icon: "/images/valorant-points-icon.webp" }),
        variant("11475 Points", 1129737, { icon: "/images/valorant-points-icon.webp" }),
        variant("12000 Points", 1184512, { icon: "/images/valorant-points-icon.webp" }),
        variant("13050 Points", 1294062, { icon: "/images/valorant-points-icon.webp" }),
        variant("14650 Points", 1455453, { icon: "/images/valorant-points-icon.webp" }),
        variant("16700 Points", 1674554, { icon: "/images/valorant-points-icon.webp" }),
        variant("18400 Points", 1840835, { icon: "/images/valorant-points-icon.webp" }),
        variant("20000 Points", 2002225, { icon: "/images/valorant-points-icon.webp" }),
        variant("22000 Points", 2149922, { icon: "/images/valorant-points-icon.webp" }),
      ],
    },
    {
      emoji: "",
      label: "Region MY (Malaysia)",
      items: [
        variant("475 VP", 81173, { icon: "/images/valorant-points-icon.webp" }),
        variant("1000 VP", 167059, { icon: "/images/valorant-points-icon.webp" }),
        variant("2050 VP", 325948, { icon: "/images/valorant-points-icon.webp" }),
        variant("3650 VP", 568998, { icon: "/images/valorant-points-icon.webp" }),
        variant("5350 VP", 811627, { icon: "/images/valorant-points-icon.webp" }),
        variant("11000 VP", 1627126, { icon: "/images/valorant-points-icon.webp" }),
      ],
    },
    {
      emoji: "",
      label: "Region TH (Thailand)",
      items: [
        variant("475 VP", 75168, { icon: "/images/valorant-points-icon.webp" }),
        variant("1000 VP", 150336, { icon: "/images/valorant-points-icon.webp" }),
        variant("3650 VP", 531877, { icon: "/images/valorant-points-icon.webp" }),
        variant("5350 VP", 763129, { icon: "/images/valorant-points-icon.webp" }),
        variant("11000 VP", 1526211, { icon: "/images/valorant-points-icon.webp" }),
      ],
    },
    {
      emoji: "",
      label: "Region PH (Philipina)",
      items: [
        variant("475 VP", 57646, { icon: "/images/valorant-points-icon.webp" }),
        variant("1000 VP", 115581, { icon: "/images/valorant-points-icon.webp" }),
        variant("2050 VP", 231450, { icon: "/images/valorant-points-icon.webp" }),
        variant("3650 VP", 405254, { icon: "/images/valorant-points-icon.webp" }),
        variant("5350 VP", 579058, { icon: "/images/valorant-points-icon.webp" }),
        variant("11000 VP", 1158405, { icon: "/images/valorant-points-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Valorant",
  descriptionIntro: "Top up point Valorant harga paling murah. Cara topup Valorant termurah :",
  descriptionSteps: [
    "Masukkan Riot ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "VP otomatis masuk ke akun game",
  ],
};

const WEREWOLF_PARTY_GAME: GameDetail = {
  slug: "werewolf-party-game",
  name: "Werewolf (Party Game)",
  publisher: "Walkman",
  image: "/games/werewolf-party-game.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  usernameLabel: "Username",
  usernamePosition: "after",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("6 Diamonds", 1994, { icon: null }),
        variant("10 Diamonds", 2992, { icon: null }),
        variant("15 Diamonds", 4532, { icon: null }),
        variant("16 Diamonds", 4986, { icon: null }),
        variant("30 Diamonds", 9063, { icon: null }),
        variant("33 Diamonds", 9970, { icon: null }),
        variant("45 Diamonds", 13595, { icon: null }),
        variant("60 Diamonds", 18126, { icon: null }),
        variant("66 Diamonds", 19939, { icon: null }),
        variant("75 Diamonds", 22658, { icon: null }),
        variant("99 Diamonds", 29908, { icon: null }),
        variant("135 Diamonds", 40784, { icon: null }),
        variant("150 Diamonds", 45315, { icon: null }),
        variant("165 Diamonds", 49847, { icon: null }),
        variant("198 Diamonds", 59816, { icon: null }),
        variant("225 Diamonds", 67973, { icon: null }),
        variant("300 Diamonds", 90630, { icon: null }),
        variant("330 Diamonds", 99693, { icon: null }),
        variant("495 Diamonds", 149540, { icon: null }),
        variant("900 Diamonds", 271890, { icon: null }),
        variant("990 Diamonds", 299079, { icon: null }),
        variant("1500 Diamonds", 453150, { icon: null }),
        variant("1650 Diamonds", 498465, { icon: null }),
        variant("3000 Diamonds", 906300, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Werewolf (Party Game)",
  descriptionIntro:
    "Top up diamond Werewolf Party Game harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore. Cara topup Werewolf Party Game via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis diamond masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const ZEPETO: GameDetail = {
  slug: "zepeto",
  name: "Zepeto",
  publisher: "NEVER Z Corp",
  image: "/games/zepeto.webp",
  rating: 5.0,
  ratingCount: "304",
  idLabel: "ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Special Items",
      items: [variant("Premium 1M", 50528, { icon: null })],
    },
    {
      emoji: "",
      label: "Top Up Zemz",
      items: [
        variant("7 ZEMS", 7049, { icon: null }),
        variant("14 ZEMS", 14098, { icon: null }),
        variant("28 ZEMS", 27352, { icon: null }),
        variant("58 ZEMS", 54701, { icon: null }),
        variant("128 ZEMS", 119052, { icon: null }),
        variant("323 ZEMS", 301652, { icon: null }),
        variant("1000 ZEMS", 897323, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Top Up Coins",
      items: [
        variant("4680 Coins", 14098, { icon: null }),
        variant("9700 Coins", 27352, { icon: null }),
        variant("25200 Coins", 68375, { icon: null }),
        variant("40700 Coins", 110204, { icon: null }),
        variant("110000 Coins", 289586, { icon: null }),
        variant("300000 Coins", 787029, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Zepeto",
  descriptionIntro:
    "Top up zems & coin Zepeto harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore. Cara topup Zepeto via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis zems / coin masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

export const GAME_DETAILS_7: Record<string, GameDetail> = {
  [RAGNAROK_ORIGIN.slug]: RAGNAROK_ORIGIN,
  [RAGNAROK_X.slug]: RAGNAROK_X,
  [REVELATION_INFINITE_JOURNEY.slug]: REVELATION_INFINITE_JOURNEY,
  [SAUSAGE_MAN.slug]: SAUSAGE_MAN,
  [SCROLL_OF_ONMYOJI_SAKURA_SWORD.slug]: SCROLL_OF_ONMYOJI_SAKURA_SWORD,
  [SPEED_DRIFTERS.slug]: SPEED_DRIFTERS,
  [STATE_OF_SURVIVAL_ZOMBIE_WAR.slug]: STATE_OF_SURVIVAL_ZOMBIE_WAR,
  [STORMSHOT.slug]: STORMSHOT,
  [SUPER_SUS.slug]: SUPER_SUS,
  [TIME_RAIDERS.slug]: TIME_RAIDERS,
  [TOM_AND_JERRY_CHASE.slug]: TOM_AND_JERRY_CHASE,
  [TOWER_BRAWL.slug]: TOWER_BRAWL,
  [VALORANT.slug]: VALORANT,
  [WEREWOLF_PARTY_GAME.slug]: WEREWOLF_PARTY_GAME,
  [ZEPETO.slug]: ZEPETO,
};
