import type { GameDetail } from "@/types/game";
import { variant, createPaymentGroups } from "./game-detail-helpers";

const HATSUNE_MIKU_COLORFUL_STAGE: GameDetail = {
  slug: "hatsune-miku-colorful-stage",
  name: "Hatsune Miku : Colorful Stage",
  publisher: "SEGA",
  image: "/games/hatsune-miku-colorful-stage.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "AID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("Crystals x 50", 5881, { icon: null }),
        variant("Crystals A x 110", 12887, { icon: null }),
        variant("Crystals B x 350", 39464, { icon: null }),
        variant("Crystals C x 950", 103893, { icon: null }),
        variant("Crystals D x 1800", 200538, { icon: null }),
        variant("Crystals E x 3060", 321344, { icon: null }),
        variant("Crystals F x 5000", 522686, { icon: null }),
        variant("Crystals G x 10500", 1046178, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Hatsune Miku : Colorful Stage",
  descriptionIntro:
    "Top up Hatsune Miku : Colorful Stage harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO.",
  descriptionSteps: [
    "Cara topup :",
    "1) Masukkan Data Akun",
    "2) Pilih Nominal",
    "3) Tentukan Jumlah Pembelian",
    "4) Pilih Pembayaran",
    "5) Masukkan Kode Promo (jika ada)",
    "6) Isi Detail Kontak",
    "7) Klik Pesan Sekarang dan lakukan Pembayaran",
    "8) Selesai",
  ],
};

const HEROES_EVOLVED: GameDetail = {
  slug: "heroes-evolved",
  name: "Heroes Evolved",
  publisher: "NETDRAGON WEBSOFT (HONG KONG) LIMITED",
  image: "/games/heroes-evolved.webp",
  rating: 5.0,
  ratingCount: "16",
  idLabel: "ID",
  idTooltip:
    "Anda dapat menemukan playerid Anda dari \"Pengaturan\" di layar kanan atas dan tekan \"ID PEMAIN\". Contoh : 12345abcdef12346abcdefg#16124000/101/23.2.1.3",
  serverLabel: "Server",
  serverOptions: [
    "North America - LOST TEMPLE [NA]", "North America - NEW ORDER [NA]",
    "Europe - ASGARD[EU]", "Europe - OLYMPUS[EU]",
    "South America - AMAZON [SA]", "South America - EL DORADO [SA]",
    "ASIA - S1.ANGKOR [AS]", "ASIA - S2.EL NIDO [AS]", "ASIA - ไทย[TH]", "ASIA - SHANGRI-LA [AS]", "ASIA - ไทยแลนด์[TH]",
  ],
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("100 Tokens", 15603, { icon: null }),
        variant("240 Tokens", 37661, { icon: null }),
        variant("500 Tokens", 78631, { icon: null }),
        variant("1200 Tokens", 157420, { icon: null }),
        variant("2500 Tokens", 314995, { icon: null }),
        variant("6500 Tokens", 787724, { icon: null }),
        variant("14000 Tokens", 1575604, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Heroes Evolved",
  descriptionIntro: "Top up token Heroes Evolved harga paling murah. Cara beli token Heroes Evolved termurah :",
  descriptionSteps: [
    "Masukkan ID & pilih Server",
    "Pilih Nominal",
    "Pilih Metode Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Token masuk otomatis ke akun Anda",
  ],
};

const HONKAI_IMPACT_3: GameDetail = {
  slug: "honkai-impact-3",
  name: "Honkai Impact 3",
  publisher: "miHoYo",
  image: "/games/honkai-impact-3.webp",
  rating: 5.0,
  ratingCount: "74",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Special Item",
      items: [variant("Monthly-Card", 79347, { icon: "/images/honkai-impact-3-monthly-card-icon.webp" })],
    },
    {
      emoji: "",
      label: "Crystals",
      items: [
        variant("65 Crystals", 15587, { icon: "/images/honkai-impact-3-crystal-icon.webp" }),
        variant("330 Crystals", 79347, { icon: "/images/honkai-impact-3-crystal-icon.webp" }),
        variant("660 Crystals", 158692, { icon: "/images/honkai-impact-3-crystal-icon.webp" }),
        variant("1320 Crystals", 314548, { icon: "/images/honkai-impact-3-crystal-icon.webp" }),
      ],
    },
    {
      emoji: "",
      label: "B-Chips",
      items: [
        variant("30 B-Chips", 7936, { icon: "/images/honkai-impact-3-bchip-icon.webp" }),
        variant("65 B-Chips", 15587, { icon: "/images/honkai-impact-3-bchip-icon.webp" }),
        variant("330 B-Chips", 79347, { icon: "/images/honkai-impact-3-bchip-icon.webp" }),
        variant("990 B-Chips", 235203, { icon: "/images/honkai-impact-3-bchip-icon.webp" }),
        variant("1320 B-Chips", 314548, { icon: "/images/honkai-impact-3-bchip-icon.webp" }),
        variant("1980 B-Chips", 473240, { icon: "/images/honkai-impact-3-bchip-icon.webp" }),
        variant("3300 B-Chips", 793454, { icon: "/images/honkai-impact-3-bchip-icon.webp" }),
        variant("6600 B-Chips", 1558569, { icon: "/images/honkai-impact-3-bchip-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Honkai Impact 3",
  descriptionIntro:
    "Top up Honkai Impact 3 resmi miHoYo harga paling murah. Cara beli crystal dan b-chip Honkai Impact 3 termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Metode Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "B-Chip/Crystal masuk otomatis ke akun Anda",
  ],
};

const HONOR_OF_KINGS: GameDetail = {
  slug: "honor-of-kings",
  name: "Honor of Kings",
  publisher: "Tencent Games",
  image: "/games/honor-of-kings.webp",
  rating: 4.99,
  ratingCount: "10.06rb",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("16 Tokens", 3266, { icon: null }),
        variant("80 Tokens", 16329, { icon: null }),
        variant("240 Tokens", 49370, { icon: null }),
        variant("400 Tokens", 82218, { icon: null }),
        variant("560 Tokens", 115260, { icon: null }),
        variant("800 Tokens", 164628, { icon: null }),
        variant("1200 Tokens", 247038, { icon: null }),
        variant("2400 Tokens", 494267, { icon: null }),
        variant("4000 Tokens", 823905, { icon: null }),
        variant("8000 Tokens", 1648001, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Honor of Kings",
  descriptionIntro:
    "Top up token Honor of Kings Global harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO. Cara topup Honor of Kings via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis tokens masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const IDENTITY_V: GameDetail = {
  slug: "identity-v",
  name: "Identity V",
  publisher: "NetEase",
  image: "/games/identity-v.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "Id",
  serverLabel: "Server",
  serverOptions: ["Asia", "NA and EU"],
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("60 Echoes", 19158, { icon: null }),
        variant("185 Echoes", 54022, { icon: null }),
        variant("305 Echoes", 97699, { icon: null }),
        variant("690 Echoes", 190608, { icon: null }),
        variant("2025 Echoes", 573546, { icon: null }),
        variant("3330 Echoes", 955910, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Identity V",
  descriptionIntro: "Top up Echoes Identity V harga paling murah, aman, cepat, dan terpercaya. Cara topup Echoes Identity V:",
  descriptionSteps: [
    "1. Masukkan ID",
    "2. Pilih Nominal",
    "3. Masukkan jumlah",
    "4. Pilih Pembayaran",
    "5. Tulis Kode Promo (jika ada)",
    "6. Masukkan No WhatsApp",
    "7. Klik Order Now & lakukan Pembayaran",
    "8. Echoes otomatis masuk ke akun game",
  ],
};

const IDLE_LEGENDS_SERVER_OPTIONS: string[] = [
  "S1-Ragnarok", "S10-Harpy", "S100-Dakini", "S101-Kali", "S102-Goemon", "S103-Eligor", "S104-Thoth", "S105-Barong", "S106-Rangda", "S107-Berith",
  "S108-Orobas", "S109-Carmen", "S11-Catherine", "S110-Parvati", "S111-Ishtar", "S112-Agathion", "S113-Melchizedek", "S114-Dominion", "S115-Uriel", "S116-Bicorn",
  "S117-Naga", "S118-Ariadne", "S119-Fortuna", "S12-Gandalf", "S120-Asterius", "S121-Europa", "S122-Lakshmi", "S123-Norn", "S124-Kelpie", "S125-Rakshasha",
  "S126-Siegfried", "S127-Orthrus", "S128-Hecatoncheir", "S129-Moloch", "S13-Witch Racun", "S130-Pisaca", "S131-Chernobog", "S132-Baal", "S133-Ardha", "S134-Incubus",
  "S135-Andras", "S136-Flauros", "S137-Lilim", "S138-Samael", "S139-Nebiros", "S14-Doomsayer", "S140-Belial", "S141-Beelzebub", "S142-Belphegor", "S143-Seth",
  "S144-Mara", "S145-Ananta", "S146-Garuda", "S147-Hanuman", "S148-Sraosha", "S149-Yurlungur", "S15-Sorceress", "S150-Mithras", "S151-Quetzalcoatl", "S152-Messiah",
  "S153-Sol", "S154-Hodr", "S155-Lodurr", "S156-Gullveig", "S157-Nidhogg", "S158-Skoll", "S159-Hati", "S16-Medea", "S160-Surt", "S161-Garm",
  "S162-Valhalla", "S163-Draugr", "S164-Gleipnir", "S165-Sleipnir", "S166-Huginn", "S167-Muninn", "S168-Fossegrim", "S169-Ratatoskr", "S17-Idron", "S170-Yggdrasil",
  "S171-Jotunheimen", "S172-Borr", "S173-Idun", "S174-Bragi", "S175-Forseti", "S176-Gjallarhorn", "S177-Vali", "S178-Nerthus", "S179-Ullr", "S18-Hellfire",
  "S180-Sif", "S181-Glitnir", "S182-Hermod", "S183-Gefjun", "S184-Fjorgynn", "S185-Orthus", "S186-Thessaly", "S187-Crethus", "S188-Alcimede", "S189-Sidero",
  "S19-Otto", "S190-Argonauts", "S191-Colchis", "S192-Argos", "S193-Iolaus", "S194-Lemnos", "S195-Niflheim", "S196-Ymir", "S197-Vili", "S198-Frigg",
  "S199-Balder", "S2-Naga Frost", "S20-Sur", "S200-Heimdall", "S201-Freyja", "S202-Bifrost", "S203-Vidar", "S204-Alfheim", "S205-Dokkalfar", "S206-Ljosalfar",
  "S207-Svartalfheim", "S208-Mjollnir", "S209-Draupnir", "S21-Witch", "S210-Gungnir", "S211-Skidbladnir", "S212-Austri", "S213-Vestri", "S214-Nordri", "S215-Sudri",
  "S216-Jotnar", "S217-Raka", "S218-Puramdhi", "S219-Parendi", "S22-Necromancer", "S220-Bharati", "S221-Mahi", "S222-Rigveda", "S223-Purana", "S224-Itihasa",
  "S225-Vayu", "S226-Anila", "S227-Tanuna", "S228-Pavana", "S229-Vishvakarma", "S23-Lilith", "S230-Bharata", "S231-Kapila", "S232-Lokapala", "S233-Mitra",
  "S234-Varuna", "S235-Brhaspati", "S236-Atum", "S237-Shu", "S238-Tefnut", "S239-Nephthys", "S24-Pixie", "S240-Imset", "S241-Hapi", "S242-Iah",
  "S243-Khonsu", "S244-Kagemni", "S245-Khnum", "S246-Khepri", "S247-Maahes", "S248-Pakhet", "S249-Merwel", "S25-Loki", "S250-Nefertum", "S251-Onuris",
  "S252-Mafdet", "S253-Peteese", "S254-Ogdoad", "S255-Pataikos", "S256-Meyht", "S257-Pihor", "S258-Qadesh", "S259-Mehen", "S26-Seraphim", "S260-Raettawy",
  "S261-Sokar", "S262-Mekhit", "S263-Raharakty", "S264-Sothis", "S265-Shay", "S266-Mnevis", "S267-Triads", "S268-Serqet", "S269-Tatenen", "S27-Dracula",
  "S270-Reshep", "S271-Shezmu", "S272-Tetrads", "S273-Vishnu", "S274-Shiva", "S275-Ganesha", "S276-Rama", "S277-Krishna", "S278-Durga Devi", "S279-Indra",
  "S28-Karzan", "S280-Surya", "S281-Agni", "S282-Soma", "S283-Rudra", "S284-Prajapati", "S285-Ushas", "S286-Prithvi", "S287-Aditi", "S288-Vac",
  "S289-Nirhti", "S29-Valkyrie", "S290-Ratri", "S291-Carbunclo", "S292-Tanuki", "S293-Fenghuang", "S294-Strix", "S295-Chamrosh", "S296-Simurgh", "S297-Chalkydri",
  "S298-Roc", "S299-Cetan", "S3-Nereid", "S30-Succubus", "S300-Piasa", "S301-Alicanto", "S302-Alkonost", "S303-Oozlum", "S304-Nyctimene", "S305-Nachtkrapp",
  "S306-Minokawa", "S307-Itsumade", "S308-Aethon", "S309-Adarna", "S31-Fenrir", "S310-Callisto", "S311-Vetala", "S312-Tjinimin", "S313-Minyades", "S314-Leutogi",
  "S315-Camazotz", "S316-Chupacabra", "S317-Balayang", "S318-Selket", "S319-Pabilsag", "S32-Thor", "S320-Karkinos", "S321-Jorogumo", "S322-Anansi", "S323-Selkie",
  "S324-Kushtaka", "S325-Encantado", "S326-Ganga", "S327-Gayatri", "S328-Daksha", "S329-Amaterasu", "S33-Iset", "S330-Uzume", "S331-Oni", "S332-Hachiman",
  "S333-Izanagi", "S334-Ninigi", "S335-Omoikane", "S336-Raijin", "S337-Susanoo", "S338-Tenjin", "S339-Virgo", "S34-Lucifer", "S340-Libra", "S341-Scorpio",
  "S342-Phigalia", "S343-Othreis", "S344-Cyllene", "S345-Morea", "S346-Claia", "S347-Khelone", "S348-Karya", "S349-Sagitta", "S35-Hel", "S350-Aquila",
  "S351-Lyra", "S352-Cygnus", "S353-Crater", "S354-Corvus", "S355-Ophiuchus", "S356-Euryale", "S357-Phoenicis", "S358-Pictoris", "S359-Chevalet", "S36-Darklord",
  "S360-Pyxis", "S361-Ekho", "S362-Heliades", "S363-Ampelos", "S364-Balanis", "S365-Atlanteia", "S366-Daphnis", "S367-Evadne", "S368-Regulus", "S369-Meleph",
  "S37-Ix", "S370-Saclateni", "S371-Talitha", "S372-Genitive", "S373-Arcas", "S374-Volans", "S375-Lacaille", "S376-Ceti", "S377-Circini", "S378-Elektra",
  "S379-Celeste", "S38-Grim Reaper", "S380-Aurora", "S381-Nova", "S382-Alkes", "S383-Muscida", "S384-Arche", "S385-Polaris", "S386-Sirius", "S387-Betelgeuse",
  "S388-Rigel", "S389-Vega", "S39-Pangeran Elf", "S390-Antares", "S391-Canopus", "S392-Bima", "S393-Arjuna", "S394-Nakula", "S395-Sadewa", "S396-Siliwangi",
  "S397-Purbasari", "S398-JakaTingkir", "S399-MakLampir", "S4-Illsya", "S40-Hecate", "S400-Alpha", "S401-Beta", "S402-Felis", "S403-Kraz", "S404-Jabbah",
  "S405-Intercrus", "S406-Mirach", "S407-Meteor", "S408-Finlay", "S409-Antaboga", "S41-Lycan", "S410-Jonggrang", "S411-Scuti", "S412-Lacerta", "S413-Plancius",
  "S414-Togog", "S415-Gundala", "S416-Taurus", "S417-Hesperos", "S418-Sweta", "S419-Madri", "S42-Kinnara", "S420-Surasena", "S421-Auriga", "S422-TimunMas",
  "S423-Yudhistira", "S424-Gemini", "S425-Jupiter", "S426-Pleione", "S427-Nuada", "S428-Scheat", "S429-Uttara", "S43-Ranger", "S430-AnglingDharma", "S431-Fornax",
  "S432-Draco", "S433-Lundmark", "S434-Zwicky", "S435-Triplet", "S436-Sekhmet", "S437-Leporis", "S438-Teiwaz", "S439-Parumleo", "S44-Infanteri Orc", "S440-Avior",
  "S441-Albali", "S442-Ascella", "S443-Cassiopeia", "S444-Cetus", "S445-Damayanti", "S446-Oberon", "S447-Serpens", "S448-Aquarius", "S449-Capricorn", "S45-Faen",
  "S450-Cepheus", "S451-Aries", "S452-Cancer", "S453-Leo", "S454-Sagittarius", "S455-Centaurus", "S456-Lupus", "S457-Uluka", "S458-Byasa", "S459-Taksaka",
  "S46-Titan", "S460-Nala", "S461-Bajradata", "S462-Kirmira", "S463-Bisma", "S464-Sonaka", "S465-Kertawarma", "S466-Supriya", "S467-Satyawati", "S468-Kicaka",
  "S469-Balarama", "S47-Phoenix", "S470-Rukmi", "S471-Satyajit", "S472-Kindama", "S473-Jatasura", "S474-Aswatama", "S475-Bahlika", "S476-Sangkuni", "S477-Irawan",
  "S478-Aniruda", "S48-Odin", "S49-Gaiming", "S5-Merlin Muda", "S50-Gaia", "S51-Abaddon", "S52-Arthur", "S53-Raynor", "S54-Tyr", "S55-Ksatria Hitam",
  "S56-Destroyer", "S57-Gilgamesh", "S58-Doomguard", "S59-Griffin", "S6-Balrog", "S60-Treant", "S61-Golem", "S62-Galene", "S63-Pisces", "S64-Galadriel",
  "S65-Pan", "S66-Raphael", "S67-Alleria", "S68-Oracle", "S69-Satyr", "S7-Anubis", "S70-Bard", "S71-Luna", "S72-Shaman", "S73-Sylph",
  "S74-Fairy", "S75-Hephaetus", "S76-Zephyrus", "S77-Uranus", "S78-Plutus", "S79-Eurus", "S8-Messa", "S80-Cronus", "S81-Castor", "S82-Attis",
  "S83-Calypso", "S84-Eileithyia", "S85-Circe", "S86-Choronzon", "S87-Queen Mab", "S88-Chu Chulainn", "S89-Apsaras", "S9-Mage Salju", "S90-Horus", "S91-Osiris",
  "S92-Scathach", "S93-Sarasvati", "S94-Cybele", "S95-Skadi", "S96-Ashtoreth", "S97-Asherah", "S98-Lamia", "S99-Hariti",
];

const IDLE_LEGENDS: GameDetail = {
  slug: "idle-legends-gods-saga",
  name: "Idle Legends : GODS SAGA",
  publisher: "Eyougame",
  image: "/games/idle-legends-gods-saga.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idTooltip: "ID Pengguna Anda dapat ditemukan di situs web Eyougame setelah masuk",
  serverLabel: "Server",
  serverOptions: IDLE_LEGENDS_SERVER_OPTIONS,
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("90 Diamonds", 15073, { icon: null }),
        variant("450 Diamonds", 75361, { icon: null }),
        variant("900 Diamonds", 150721, { icon: null }),
        variant("1350 Diamonds", 226080, { icon: null }),
        variant("1840 Diamonds", 301440, { icon: null }),
        variant("5000 Diamonds", 753599, { icon: null }),
        variant("10000 Diamonds", 1507198, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Idle Legends : GODS SAGA",
  descriptionIntro: "Top Up Diamond Idle Legends harga paling murah. Cara topup dm Idle Legends termurah :",
  descriptionSteps: [
    "Masukkan ID & pilih Server",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Diamond masuk otomatis ke akun Anda",
  ],
};

const INFINITE_BORDERS: GameDetail = {
  slug: "infinite-borders",
  name: "Infinite Borders",
  publisher: "NetEase",
  image: "/games/infinite-borders.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("73 (72+1) Jades", 17220, { icon: null }),
        variant("292 (288+4) Jades", 62535, { icon: null }),
        variant("732 (720+12) Jades", 153165, { icon: null }),
        variant("1464 (1440+24) Jades", 316299, { icon: null }),
        variant("3850 (3790+60) Jades", 724134, { icon: null }),
        variant("7270 (7150+120) Jades", 1539804, { icon: null }),
        variant("14590 (14350+240) Jades", 2989884, { icon: null }),
        variant("2870 (28310+470 ) Jades", 5980674, { icon: null }),
        variant("72700 (71500+1200) Jades", 14499894, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Infinite Borders",
  descriptionIntro: "Top up Infinite Borders harga paling murah. Cara topup Infinite Borders termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Jades otomatis masuk ke akun game",
  ],
};

const JADE_LEGENDS_SERVER_OPTIONS: string[] = [
  "Jade", "Legends", "Norn", "Europa", "Lakshmi", "Chandra", "Agni", "Narada", "Uluka", "Byasa",
  "Damayanti", "Taksaka", "Sweta", "Nala", "Madri", "Bajradata", "Surasena", "Kirmira", "Bisma", "Sonaka",
  "Kertawarma", "Supriya", "Satyawati", "Kicaka", "Balarama", "Rukmi", "Satyajit", "Kindama", "Jatasura", "Aswatama",
  "Bahlika", "Sangkuni", "Irawan", "Aniruda", "Rewati", "Hidimba", "Brahala", "Othreis", "Cyllene", "Morea",
  "Claia", "Khelone", "Karya", "Heliades", "Ekho", "Subhadra", "Madravti", "Uttara", "Satanika", "Kichaka",
  "Sudeshna", "Virata", "Klenting", "ButoPrepat", "MbokSrini", "TimunMas", "SiKancil", "Guriang", "Ratih", "Rarasati",
  "DayangSumbi", "Tumang", "Wayungyang", "Bondowoso", "Sangkuriang", "Antaboga", "Togog", "HyangSita", "RoroMendut", "PrabuBaka",
  "Durga", "Jonggrang", "NyaiDasima", "Gundala", "Surapati", "Triads", "Mnevis", "Shay", "Sothis", "Raharakty",
  "MakLampir", "Madangkara", "DamarWulan", "Mandrawata", "WiroSableng", "JakaTingkir", "Purbasari", "AnglingDharma", "Siliwangi", "Sadewa",
  "Nakula", "Arjuna", "Bima", "Yudhistira", "Gatotkaca", "Sol", "Fjorgynn", "Gefjun", "Hermod", "Glitnir",
  "Sif", "Ullr", "Nerthus", "Vali", "Gjallarhorn", "Forseti", "Bragi", "Idun", "Borr", "Jotunheimen",
  "Yggdrasil", "Ratatoskr", "Fossegrim", "Midgard", "Muninn", "Sigbin", "Barghest", "Salawa", "Hippogriff", "Gamayun",
  "Tengu", "Strix", "Sirin", "Chamrosh", "Simurgh", "Tetrads", "Shezmu", "Reshep", "Tatenen", "Serqet",
  "Ophiel", "Telantes", "Mihr", "Conah", "Briar", "Iamus", "Hyacinthus", "Evadne", "Geryon", "Eryx",
  "Endymion", "Deucalion", "Danae", "Cyrene", "Cecrops", "Eligor", "Goemon", "Kali", "Dakini", "Hariti",
  "Lamia", "Asherah", "Ashtoreth", "Skadi", "Cybele", "Hoenir", "Aesir", "Garm", "Surt", "Hati",
  "Skoll", "Nidhogg", "Gullveig", "Lodurr", "Amene", "Amenet", "Aken", "Neith", "Sekhmet", "Heka",
  "Qebhet", "Bastet", "Hathor", "Ra", "Amun", "Regulus", "Pleione", "Mirach", "Maia", "Intercrus",
  "Jabbah", "Kraz", "Felis", "Beta", "Alpha", "Euryale", "Asclepius", "Muscae", "Therium", "Bestia",
  "Leporis", "Hevelius",
];

const JADE_LEGENDS: GameDetail = {
  slug: "jade-legends",
  name: "Jade Legends",
  publisher: "EYOUGAME",
  image: "/games/jade-legends.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idTooltip: "Untuk menemukan ID Pengguna Anda, masuk ke game dan ketuk ikon eyougame di kiri atas > pengguna",
  usernameLabel: "Username",
  usernamePosition: "after",
  serverLabel: "Server",
  serverOptions: JADE_LEGENDS_SERVER_OPTIONS,
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Kartu Bulanan",
      items: [
        variant("Kartu Bulanan Joy", 84099, { icon: null }),
        variant("Kartu Bulanan Supreme", 168196, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("90 Jade", 16821, { icon: null }),
        variant("450 Jade", 84099, { icon: null }),
        variant("900 Jade", 168196, { icon: null }),
        variant("1350 Jade", 252293, { icon: null }),
        variant("1800 Jade", 336390, { icon: null }),
        variant("2800 Jade", 504586, { icon: null }),
        variant("4800 Jade", 840976, { icon: null }),
        variant("9800 Jade", 1681950, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Jade Legends",
  descriptionIntro: "Top up Jade Legends: Immortal Realm harga paling murah. Cara top up Jade Legends termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Jade masuk otomatis ke akun Anda",
  ],
};

const KING_OF_AVALON: GameDetail = {
  slug: "king-of-avalon",
  name: "King of Avalon",
  publisher: "FunPlus International AG",
  image: "/games/king-of-avalon.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("500 Diamonds", 73673, { icon: null }),
        variant("1000 Diamonds", 148280, { icon: null }),
        variant("2000 Diamonds", 306795, { icon: null }),
        variant("5000 Diamonds", 745038, { icon: null }),
        variant("10000 Diamonds", 1490965, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi King of Avalon",
  descriptionIntro:
    "Top up King of Avalon diamond harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO. Cara topup King of Avalon via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis diamond masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

export const GAME_DETAILS_4: Record<string, GameDetail> = {
  [HATSUNE_MIKU_COLORFUL_STAGE.slug]: HATSUNE_MIKU_COLORFUL_STAGE,
  [HEROES_EVOLVED.slug]: HEROES_EVOLVED,
  [HONKAI_IMPACT_3.slug]: HONKAI_IMPACT_3,
  [HONOR_OF_KINGS.slug]: HONOR_OF_KINGS,
  [IDENTITY_V.slug]: IDENTITY_V,
  [IDLE_LEGENDS.slug]: IDLE_LEGENDS,
  [INFINITE_BORDERS.slug]: INFINITE_BORDERS,
  [JADE_LEGENDS.slug]: JADE_LEGENDS,
  [KING_OF_AVALON.slug]: KING_OF_AVALON,
};
