import type { GameDetail } from "@/types/game";
import { variant, createPaymentGroups } from "./game-detail-helpers";

const METAL_SLUG_AWAKENING: GameDetail = {
  slug: "metal-slug-awakening",
  name: "Metal Slug : Awakening",
  publisher: "VNGGAMES",
  image: "/games/metal-slug-awakening.webp",
  rating: 5.0,
  ratingCount: "180",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Pickaxe",
      items: [
        variant("Alloy Pickaxe x1", 23563, { icon: null }),
        variant("Ruby Pickaxe x1", 27926, { icon: null }),
        variant("Sapphire Pickaxe x1", 27926, { icon: null }),
        variant("Alloy Pickaxe x10", 235624, { icon: null }),
        variant("Ruby Pickaxe x10", 279257, { icon: null }),
        variant("Sapphire Pickaxe x10", 279257, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Special Items",
      items: [
        variant("Kartu Bulanan", 61088, { icon: "/images/metal-slug-monthly-card-icon.webp" }),
        variant("Support Pass", 61088, { icon: null }),
        variant("Premium Support Pass", 117812, { icon: null }),
        variant("Kartu Bulanan Premium", 117812, { icon: "/images/metal-slug-monthly-card-premium-icon.webp" }),
      ],
    },
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("60 Ruby", 13091, { icon: "/images/metal-slug-ruby-icon.webp" }),
        variant("310 Ruby", 61088, { icon: "/images/metal-slug-ruby-icon.webp" }),
        variant("630 Ruby", 117812, { icon: "/images/metal-slug-ruby-icon.webp" }),
        variant("1300 Ruby", 235624, { icon: "/images/metal-slug-ruby-icon.webp" }),
        variant("3200 Ruby", 610874, { icon: "/images/metal-slug-ruby-icon.webp" }),
        variant("6500 Ruby", 1178114, { icon: "/images/metal-slug-ruby-icon.webp" }),
      ],
    },
    {
      emoji: "",
      label: "Topup Manual",
      items: [
        variant("10 Ruby", 2183, { icon: "/images/metal-slug-ruby-icon.webp" }),
        variant("24 Ruby", 5237, { icon: "/images/metal-slug-ruby-icon.webp" }),
        variant("122 Ruby", 26181, { icon: "/images/metal-slug-ruby-icon.webp" }),
        variant("182 Ruby", 39271, { icon: "/images/metal-slug-ruby-icon.webp" }),
        variant("490 Ruby + 47 Sapphire", 104722, { icon: null }),
        variant("13100 Ruby + 2620 Sapphire", 2356228, { icon: null }),
        variant("19650 Ruby + 2930 Sapphire", 3490708, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Metal Slug : Awakening",
  descriptionIntro:
    "Top up Ruby Metal Slug Awakening harga paling murah, aman, cepat, dan terpercaya. Cara topup Ruby Metal Slug Awakening:",
  descriptionSteps: [
    "1. Masukkan ID",
    "2. Pilih Nominal",
    "3. Masukkan jumlah",
    "4. Pilih Pembayaran",
    "5. Tulis Kode Promo (jika ada)",
    "6. Masukkan No WhatsApp",
    "7. Klik Order Now & lakukan Pembayaran",
    "8. Ruby & items otomatis masuk ke akun game",
  ],
};

const MISTY_CONTINENT: GameDetail = {
  slug: "misty-continent",
  name: "Misty Continent",
  publisher: "FunPlus International AG",
  image: "/games/misty-continent.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("500 Diamonds", 85029, { icon: null }),
        variant("1000 Diamonds", 170342, { icon: null }),
        variant("2000 Diamonds", 341253, { icon: null }),
        variant("5000 Diamonds", 850288, { icon: null }),
        variant("10000 Diamonds", 1706261, { icon: null }),
        variant("20000 Diamonds", 3412522, { icon: null }),
        variant("50000 Diamonds", 8502867, { icon: null }),
        variant("100000 Diamonds", 17062608, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Misty Continent",
  descriptionIntro:
    "Top up Misty Continent diamond harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO. Cara topup Misty Continent via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis diamond masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const MU_ORIGIN_2: GameDetail = {
  slug: "mu-origin-2",
  name: "MU Origin 2",
  publisher: "Gamenow Technology",
  image: "/games/mu-origin-2.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "UID",
  idTooltip: "ID Pengguna Anda dapat ditemukan di menu pengaturan.",
  serverLabel: "Server",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("23 Badges", 2719, { icon: null }),
        variant("61 Badges", 7251, { icon: null }),
        variant("115 Badges", 13595, { icon: null }),
        variant("267 Badges", 31721, { icon: null }),
        variant("488 Badges", 58004, { icon: null }),
        variant("839 Badges", 99693, { icon: null }),
        variant("1297 Badges", 154071, { icon: null }),
        variant("1907 Badges", 226575, { icon: null }),
        variant("2288 Badges", 271890, { icon: null }),
        variant("6482 Badges", 770355, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi MU Origin 2",
  descriptionIntro: "Top Up Diamonds MU Origin 2",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Diamonds masuk otomatis ke akun Anda.",
  ],
};

const MU_ORIGIN_3: GameDetail = {
  slug: "mu-origin-3",
  name: "MU Origin 3",
  publisher: "FingerFun",
  image: "/games/mu-origin-3.webp",
  rating: 5.0,
  ratingCount: "2",
  idLabel: "Role ID",
  idTooltip: "ID Pengguna Anda dapat ditemukan di menu pengaturan.",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("70 Divine Diamonds", 14996, { icon: "/images/mu-origin-3-diamond-icon.webp" }),
        variant("350 Divine Diamonds", 74249, { icon: "/images/mu-origin-3-diamond-icon.webp" }),
        variant("1050 Divine Diamonds", 234034, { icon: "/images/mu-origin-3-diamond-icon.webp" }),
        variant("2100 Divine Diamonds", 450087, { icon: "/images/mu-origin-3-diamond-icon.webp" }),
        variant("3500 Divine Diamonds", 750790, { icon: "/images/mu-origin-3-diamond-icon.webp" }),
        variant("7000 Divine Diamonds", 1502466, { icon: "/images/mu-origin-3-diamond-icon.webp" }),
        variant("10500 Divine Diamonds", 2348061, { icon: "/images/mu-origin-3-diamond-icon.webp" }),
        variant("14000 Divine Diamonds", 3099736, { icon: "/images/mu-origin-3-diamond-icon.webp" }),
        variant("21000 Divine Diamonds", 4697087, { icon: "/images/mu-origin-3-diamond-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi MU Origin 3",
  descriptionIntro: "Top up diamond MU Origin 3 harga paling murah. Cara topup MU Origin 3 termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Diamonds otomatis masuk ke akun game",
  ],
};

const NEVER_AFTER: GameDetail = {
  slug: "never-after",
  name: "Never After",
  publisher: "NetEase",
  image: "/games/never-after.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Special Items",
      items: [
        variant("Daily Specials", 16292, { icon: null }),
        variant("Daily Feedback", 49992, { icon: null }),
        variant("Promotion Pass", 65489, { icon: null }),
        variant("Daily Selection", 84860, { icon: null }),
        variant("Senior Adventurer", 84860, { icon: null }),
        variant("Premium Pass", 173968, { icon: null }),
        variant("Upgrade Awards", 173968, { icon: null }),
        variant("Growth Fund", 220458, { icon: null }),
        variant("Great Adventure", 259200, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("69 Diamonds", 16292, { icon: null }),
        variant("349+17 Diamonds", 84860, { icon: null }),
        variant("629+41 Diamonds", 154596, { icon: null }),
        variant("1049+85 Diamonds", 259200, { icon: null }),
        variant("1399+153 Diamonds", 344433, { icon: null }),
        variant("2099+254 Diamonds", 503276, { icon: null }),
        variant("3549+432 Diamonds", 851955, { icon: null }),
        variant("7299+1802 Diamonds", 1704283, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Never After",
  descriptionIntro: "Top Up Diamond Never After harga paling murah. Cara beli diamond Never After termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Diamond masuk otomatis ke akun Anda",
  ],
};

const OMEGA_LEGENDS: GameDetail = {
  slug: "omega-legends",
  name: "Omega Legends",
  publisher: "IGG",
  image: "/games/omega-legends.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idTooltip:
    "Ketuk ikon Roda Gigi di pojok kanan bawah layar dalam game, lalu ketuk tombol Akun untuk memeriksa ID IGG Anda. Lihat gambar untuk informasi lebih lanjut.",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("40 Gold", 5688, { icon: null }),
        variant("108 Gold", 14219, { icon: null }),
        variant("129 Gold", 17380, { icon: null }),
        variant("215 Gold", 28438, { icon: null }),
        variant("258 Gold", 34759, { icon: null }),
        variant("691 Gold", 85314, { icon: null }),
        variant("828 Gold", 104273, { icon: null }),
        variant("1192 Gold", 142189, { icon: null }),
        variant("1429 Gold", 173787, { icon: null }),
        variant("2441 Gold", 284377, { icon: null }),
        variant("2927 GOld", 347573, { icon: null }),
        variant("9000 Gold", 1042718, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Omega Legends",
  descriptionIntro: "Top Up Gold Omega Legends",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Gold masuk otomatis ke akun Anda.",
  ],
};

const ONE_PUNCH_MAN: GameDetail = {
  slug: "one-punch-man-the-strongest",
  name: "One Punch Man : The Strongest",
  publisher: "FingerFun",
  image: "/games/one-punch-man-the-strongest.webp",
  rating: 4.98,
  ratingCount: "304",
  idLabel: "UID",
  idTooltip:
    "UID dan ID Server Anda dapat ditemukan di menu isi ulang di pojok kiri bawah.Contoh UID: 12345679_123456. Contoh SID: 123456",
  serverLabel: "SID",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("6 Kupon", 8824, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("5 Kupon", 9556, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("13 Kupon", 25481, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("22 Kupon", 35650, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("23 Kupon", 47777, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("54 Kupon", 89124, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("61 Kupon", 127402, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("107 Kupon", 178248, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("91 Kupon", 191103, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("214 Kupon", 356495, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("227 Kupon", 477754, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("321 Kupon", 534743, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("2669 Kupon", 4456187, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("8007 Kupon", 13594500, { icon: "/images/one-punch-man-kupon-icon.webp" }),
        variant("16013 Kupon", 27189000, { icon: "/images/one-punch-man-kupon-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi One Punch Man : The Strongest",
  descriptionIntro: "Top up coupon One Punch Man : The Strongest harga paling murah. Cara topup kupon OPM termurah :",
  descriptionSteps: [
    "Masukkan UID dan SID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Coupon otomatis masuk ke akun game",
  ],
};

const PERFECT_WORLD: GameDetail = {
  slug: "perfect-world",
  name: "Perfect World",
  publisher: "Perfect World Entertainment",
  image: "/games/perfect-world.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: ["Lotus", "Eternal", "StarLight", "Reborn"],
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("3750 Koin", 15156, { icon: null }),
        variant("7500 Koin", 30312, { icon: null }),
        variant("12500 Koin", 50520, { icon: null }),
        variant("25000 Koin", 101040, { icon: null }),
        variant("50000 Koin", 202079, { icon: null }),
        variant("75000 Koin", 303118, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Perfect World",
  descriptionIntro: "Top up koin Perfect World 2 harga paling murah. Cara topup PW 2 termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Koin otomatis masuk ke akun game",
  ],
};

const PHANTASY_STAR_ONLINE_2_NEW_GENESIS: GameDetail = {
  slug: "phantasy-star-online-2-new-genesis",
  name: "Phantasy Star Online 2 : New Genesis",
  publisher: "SEGA of America",
  image: "/games/phantasy-star-online-2-new-genesis.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "AID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("100AC Exchange Ticket", 13652, { icon: null }),
        variant("500AC Exchange Ticket", 67754, { icon: null }),
        variant("1000AC Exchange Ticket", 136518, { icon: null }),
        variant("3000AC Exchange Ticket", 394384, { icon: null }),
        variant("5150AC Exchange Ticket", 682587, { icon: null }),
        variant("10300AC Exchange Ticket", 1365174, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Phantasy Star Online 2 : New Genesis",
  descriptionIntro:
    "Top up Phantasy Star Online 2 : New Genesis harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO.",
  descriptionSteps: [
    "Masukkan Data Akun",
    "Pilih Nominal",
    "Tentukan Jumlah Pembelian",
    "Pilih Pembayaran",
    "Masukkan Kode Promo (jika ada)",
    "Isi Detail Kontak",
    "Klik Pesan Sekarang dan lakukan Pembayaran",
    "Selesai",
  ],
};

const PROJECT_ENTROPY: GameDetail = {
  slug: "project-entropy",
  name: "Project Entropy",
  publisher: "FunPlus",
  image: "/games/project-entropy.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("100 Star Chips", 19623, { icon: null }),
        variant("500 Star Chips", 98111, { icon: null }),
        variant("1000 Star Chips", 196221, { icon: null }),
        variant("2099 Star Chips", 392441, { icon: null }),
        variant("5399 Star Chips", 981100, { icon: null }),
        variant("10999 Star Chips", 1962200, { icon: null }),
        variant("21999 Star Chips", 3924400, { icon: null }),
        variant("54999 Star Chips", 9811000, { icon: null }),
        variant("109999 Star Chips", 19622000, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Project Entropy",
  descriptionIntro: "Top up Star Chips Project Entropy harga paling murah. Cara topup Project Entropy termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Star Chips otomatis masuk ke akun game",
  ],
};

const PUBG_NEW_STATE_MOBILE: GameDetail = {
  slug: "pubg-new-state-mobile",
  name: "PUBG : New State Mobile",
  publisher: "PUBG Corporation",
  image: "/games/pubg-new-state-mobile.webp",
  rating: 5.0,
  ratingCount: "6",
  idLabel: "Account ID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("300 NC", 16497, { icon: "/images/pubg-new-state-nc-icon.webp" }),
        variant("1500 + 80 NC", 83150, { icon: "/images/pubg-new-state-nc-icon.webp" }),
        variant("3600 + 250 NC", 199792, { icon: "/images/pubg-new-state-nc-icon.webp" }),
        variant("30000 + 5000 NC", 1666154, { icon: "/images/pubg-new-state-nc-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi PUBG : New State Mobile",
  descriptionIntro:
    "Top up NC PUBG : New State Mobile harga paling murah. Cara topup PUBG : New State Mobile termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "NC otomatis masuk ke akun game",
    "**Proses Manual 1-10 Menit",
  ],
};

const PUNISHING_GRAY_RAVEN: GameDetail = {
  slug: "punishing-gray-raven",
  name: "Punishing Gray Raven",
  publisher: "KURO TECHNOLOGY",
  image: "/games/punishing-gray-raven.webp",
  rating: 5.0,
  ratingCount: "124",
  idLabel: "Role ID",
  serverLabel: "Server",
  serverOptions: ["Asia-Pasific", "Europe", "North America"],
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Android",
      items: [
        variant("(Android) 5 Rainbow Cards", 13546, { icon: null }),
        variant("(Android) 28 Rainbow Cards", 64967, { icon: null }),
        variant("(Android) 34 Rainbow Cards", 81554, { icon: null }),
        variant("(Android) 59 Rainbow Cards", 132697, { icon: null }),
        variant("(Android) 71 Rainbow Cards", 158959, { icon: null }),
        variant("(Android) 119 Rainbow Cards", 269539, { icon: null }),
        variant("(Android) 299 Rainbow Cards", 677301, { icon: null }),
        variant("(Android) 600 Rainbow Cards", 1340780, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "IOS",
      items: [
        variant("(iOS) 5 Rainbow Cards", 13546, { icon: null }),
        variant("(iOS) 28 Rainbow Cards", 64967, { icon: null }),
        variant("(iOS) 34 Rainbow Cards", 81554, { icon: null }),
        variant("(iOS) 59 Rainbow Cards", 132697, { icon: null }),
        variant("(iOS) 71 Rainbow Cards", 158959, { icon: null }),
        variant("(iOS) 119 Rainbow Cards", 269539, { icon: null }),
        variant("(iOS) 299 Rainbow Cards", 677301, { icon: null }),
        variant("(iOS) 600 Rainbow Cards", 1340780, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Punishing Gray Raven",
  descriptionIntro:
    "Top up Rainbow Cards Punishing : Gray Raven harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO. Cara topup Punishing : Gray Raven via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis Rainbow Cards masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const RAGNAROK_M_ETERNAL_LOVE: GameDetail = {
  slug: "ragnarok-m-eternal-love",
  name: "Ragnarok M : Eternal Love",
  publisher: "Gravity",
  image: "/games/ragnarok-m-eternal-love.webp",
  rating: 5.0,
  ratingCount: "2",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: ["Eternal Love", "Midnight Party", "Memory of Faith", "Valhalla Glory"],
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("18 + 3 Big Cat Coins", 46222, { icon: null }),
        variant("24 + 4 Big Cat Coins", 62535, { icon: null }),
        variant("30 + 6 Big Cat Coins", 77036, { icon: null }),
        variant("60 + 12 Big Cat Coins", 151353, { icon: null }),
        variant("120 + 25 Big Cat Coins", 298173, { icon: null }),
        variant("298 + 75 Big Cat Coins", 740448, { icon: null }),
        variant("598 + 150 Big Cat Coins", 1479988, { icon: null }),
        variant("1196 + 300 Big Cat Coins", 2978102, { icon: null }),
        variant("2990 + 750 Big Cat Coins", 7420785, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Special Items",
      items: [variant("Limited Special Gift", 122351, { icon: null })],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Ragnarok M : Eternal Love",
  descriptionIntro: "Top Up Big Cat Coins Ragnarok M : Eternal Love",
  descriptionSteps: [
    "Masukkan ID dan pilih Server",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Big Cat Coins masuk otomatis ke akun Anda.",
  ],
};

const PIXEL_GUN_3D: GameDetail = {
  slug: "pixel-gun-3d",
  name: "Pixel Gun 3D",
  publisher: "Cubic Games",
  image: "/games/pixel-gun-3d.jpg",
  rating: 0,
  ratingCount: "0",
  idLabel: "AID",
  idNote: "Please make sure you fill the correct account data",
  categories: [
    {
      emoji: "",
      label: "Keys",
      items: [
        variant("55 (50+5) Keys", 14469, { icon: null }),
        variant("165 (150+15) Keys", 43699, { icon: null }),
        variant("275 (250+25) Keys", 72925, { icon: null }),
        variant("600 (500+100) Keys", 145996, { icon: null }),
        variant("1300 (1000+300) Keys", 292140, { icon: null }),
        variant("3500 (2500+1000) Keys", 730565, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Pixel Pass Tickets",
      items: [
        variant("66 (60+6) Pixel Pass tickets", 14469, { icon: null }),
        variant("200 (180+20) Pixel Pass tickets", 43699, { icon: null }),
        variant("350 (300+50) Pixel Pass tickets", 72925, { icon: null }),
        variant("750 (600+150) Pixel Pass tickets", 145996, { icon: null }),
        variant("1750 (1200+550) Pixel Pass tickets", 292140, { icon: null }),
        variant("4500 (3000+1500) Pixel Pass tickets", 730565, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Coins",
      items: [
        variant("55 (50+5) Coins", 14469, { icon: null }),
        variant("165 (150+15) Coins", 43699, { icon: null }),
        variant("275 (250+25) Coins", 72925, { icon: null }),
        variant("600 (500+100) Coins", 145996, { icon: null }),
        variant("1300 (1000+300) Coins", 292140, { icon: null }),
        variant("3500 (2500+1000) Coins", 730565, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Gems",
      items: [
        variant("100 (90+10) Gems", 43699, { icon: null }),
        variant("175 (150+25) Gems", 72925, { icon: null }),
        variant("375 (300+75) Gems", 145996, { icon: null }),
        variant("800 (600+200) Gems", 292140, { icon: null }),
        variant("2200 (1500+700) Gems", 730565, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Bundles",
      items: [
        variant("Basic Set", 72925, { icon: null }),
        variant("Advanced Set", 145996, { icon: null }),
        variant("Expert Set", 292140, { icon: null }),
        variant("Winner Set", 730565, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Pixel Gun 3D",
  descriptionIntro: "Top up Pixel Gun 3D harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO.",
  descriptionSteps: [
    "Cara topup :",
    "1) Masukkan Data Akun",
    "2) Pilih Nominal",
    "3) Tentukan Jumlah Pembelian",
    "4) Pilih Pembayaran",
    "5) Masukkan Kode Promo (jika ada)",
    "6) Isi Detail Kontak",
    "7) Klik Pesan Sekarang dan lakukan Pembayaran",
    "8) Selesai",
  ],
};

export const GAME_DETAILS_6: Record<string, GameDetail> = {
  [METAL_SLUG_AWAKENING.slug]: METAL_SLUG_AWAKENING,
  [MISTY_CONTINENT.slug]: MISTY_CONTINENT,
  [MU_ORIGIN_2.slug]: MU_ORIGIN_2,
  [MU_ORIGIN_3.slug]: MU_ORIGIN_3,
  [NEVER_AFTER.slug]: NEVER_AFTER,
  [OMEGA_LEGENDS.slug]: OMEGA_LEGENDS,
  [ONE_PUNCH_MAN.slug]: ONE_PUNCH_MAN,
  [PERFECT_WORLD.slug]: PERFECT_WORLD,
  [PHANTASY_STAR_ONLINE_2_NEW_GENESIS.slug]: PHANTASY_STAR_ONLINE_2_NEW_GENESIS,
  [PROJECT_ENTROPY.slug]: PROJECT_ENTROPY,
  [PUBG_NEW_STATE_MOBILE.slug]: PUBG_NEW_STATE_MOBILE,
  [PUNISHING_GRAY_RAVEN.slug]: PUNISHING_GRAY_RAVEN,
  [RAGNAROK_M_ETERNAL_LOVE.slug]: RAGNAROK_M_ETERNAL_LOVE,
  [PIXEL_GUN_3D.slug]: PIXEL_GUN_3D,
};
