import type { GameDetail } from "@/types/game";
import { variant, createPaymentGroups } from "./game-detail-helpers";

const EGGY_PARTY: GameDetail = {
  slug: "eggy-party",
  name: "EGGY PARTY",
  publisher: "NetEase Games",
  image: "/games/eggy-party.webp",
  rating: 5.0,
  ratingCount: "786",
  idLabel: "ID",
  idTooltip:
    "Untuk menemukan ID Pengguna Anda, klik avatar Anda di pojok kiri atas layar (lokasi ID ada di bawah nickname) . Contoh: 12345678910.",
  serverLabel: "Server",
  serverOptions: ["Asia_A", "Asia_B"],
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("10 Eggy Coins", 1994, { icon: "/images/eggy-party-coin-icon.jpeg" }),
        variant("63 (60 + 3) Eggy Coins", 12529, { icon: "/images/eggy-party-coin-icon.jpeg" }),
        variant("126 (120 + 6) Eggy Coins", 25057, { icon: "/images/eggy-party-coin-icon.jpeg" }),
        variant("324 (300 + 24) Eggy coins", 62593, { icon: "/images/eggy-party-coin-icon.jpeg" }),
        variant("757 (700 + 57) Eggy Coins", 146082, { icon: "/images/eggy-party-coin-icon.jpeg" }),
        variant("1524 (1380 + 144) Eggy Coins", 287956, { icon: "/images/eggy-party-coin-icon.jpeg" }),
        variant("2296 (2080 + 216) Eggy Coins", 433991, { icon: "/images/eggy-party-coin-icon.jpeg" }),
        variant("3873 (3450 + 423) Eggy Coins", 719842, { icon: "/images/eggy-party-coin-icon.jpeg" }),
        variant("7783 (6880 + 903) Eggy Coins", 1435570, { icon: "/images/eggy-party-coin-icon.jpeg" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi EGGY PARTY",
  descriptionIntro: "Top up Coin Eggy Party harga paling murah, aman, cepat, dan terpercaya. Cara topup Coin Eggy Party :",
  descriptionSteps: [
    "Masukkan ID dan pilih Server",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Coin otomatis masuk ke akun game",
  ],
};

const ENSEMBLE_STARS_MUSIC: GameDetail = {
  slug: "ensemble-stars-music",
  name: "Ensemble Stars Music",
  publisher: "Happy Element Limited",
  image: "/games/ensemble-stars-music.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idTooltip: "Anda dapat menemukan id pengguna Anda di aplikasi Ensemble Stars Music",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("99 EP Points", 17063, { icon: null }),
        variant("499 EP Points", 85314, { icon: null }),
        variant("1499 EP Points", 255940, { icon: null }),
        variant("2999 EP Points", 511879, { icon: null }),
        variant("4999 EP Points", 853131, { icon: null }),
        variant("9999 EP Points", 1706261, { icon: null }),
        variant("19999 EP Points", 3412522, { icon: null }),
        variant("49999 EP Points", 8531304, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Ensemble Stars Music",
  descriptionIntro: "Top up ES Points Ensemble Stars Music harga paling murah. Cara topup Ensemble Stars Music termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "ES Points otomatis masuk ke akun Anda.",
  ],
};

const EUDEMONS_ONLINE: GameDetail = {
  slug: "eudemons-online",
  name: "Eudemons Online",
  publisher: "NETDRAGON WEBSOFT (HONG KONG) LIMITED",
  image: "/games/eudemons-online.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idTooltip: "Silakan isi nama akun yang Anda gunakan untuk mendaftar Eudemons Online.",
  serverLabel: "Pilih Server",
  serverOptions: [
    "America - NewYork/Toronto", "America - LA/LasVegas", "America - Cronus", "America - Chaosacre", "America - EveGarden",
    "America - RedAltar", "America - KingGround", "America - ReturnHero", "America - Minotaur", "America - GreenMirage",
    "Europe - London", "Europe - RoseHall", "Europe - Lyra", "Europe - SongPark", "Europe - Mocci", "Europe - Lava",
    "Asia - Jin", "Asia - ElvenCity", "Asia - Draconis", "Asia - Dragon", "Asia - HeartLake", "Asia - Avita",
  ],
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("80 Points", 19907, { icon: null }),
        variant("165 Points", 39814, { icon: null }),
        variant("420 Points", 98964, { icon: null }),
        variant("680 Points", 158398, { icon: null }),
        variant("1380 Points", 316512, { icon: null }),
        variant("2650 Points", 593496, { icon: null }),
        variant("5400 Points", 1186705, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Eudemons Online",
  descriptionIntro: "Top Up Points Eudemons Online harga paling murah. Cara topup Eudemons Online termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Points masuk otomatis ke akun Anda.",
  ],
};

const FARLIGHT84: GameDetail = {
  slug: "farlight84",
  name: "Farlight84",
  publisher: "FARLIGHT",
  image: "/games/farlight84.jpg",
  rating: 5.0,
  ratingCount: "60",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("5 Diamonds", 841, { icon: null }),
        variant("10 Diamonds", 1682, { icon: null }),
        variant("20 Diamonds", 3408, { icon: null }),
        variant("30 Diamonds", 5088, { icon: null }),
        variant("40 Diamonds", 6770, { icon: null }),
        variant("50 Diamonds", 8496, { icon: null }),
        variant("60 Diamonds", 10176, { icon: null }),
        variant("80 Diamonds", 13584, { icon: null }),
        variant("100 Diamonds", 16525, { icon: null }),
        variant("165 Diamonds", 25440, { icon: null }),
        variant("220 Diamonds", 33889, { icon: null }),
        variant("330 Diamonds", 49153, { icon: null }),
        variant("880 Diamonds", 130558, { icon: null }),
        variant("2240 Diamonds", 338645, { icon: null }),
        variant("4700 Diamonds", 678129, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Farlight84",
  descriptionIntro:
    "Top up diamond Farlight 84 harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore. Cara topup Farlight 84 via ID termurah cukup dengan memasukkan ID & Server dan lakukan pembayaran, secara otomatis diamond masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const FC_MOBILE: GameDetail = {
  slug: "fc-mobile",
  name: "FC Mobile",
  publisher: "EA Spots",
  image: "/games/fc-mobile.webp",
  rating: 5.0,
  ratingCount: "1.91rb",
  idLabel: "ID",
  categories: [
    {
      emoji: "",
      label: "Silver",
      items: [
        variant("39 +4 Silver", 6428, { icon: null }),
        variant("99 +10 Silver", 15821, { icon: null }),
        variant("499 +50 Silver", 78113, { icon: null }),
        variant("999 +100 Silver", 157213, { icon: null }),
        variant("1999 +200 Silver", 325302, { icon: null }),
        variant("4999 + 500 Silver", 790018, { icon: null }),
        variant("9999 +1000 Silver", 1581024, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Fc Points",
      items: [
        variant("40+8 FC POINTS", 6428, { icon: "/images/fc-mobile-points-icon.png" }),
        variant("100+20 FC POINTS", 15821, { icon: "/images/fc-mobile-points-icon.png" }),
        variant("520+104 FC POINTS", 78113, { icon: "/images/fc-mobile-points-icon.png" }),
        variant("1070+214 FC POINTS", 157213, { icon: "/images/fc-mobile-points-icon.png" }),
        variant("2200+440 FC POINTS", 325302, { icon: "/images/fc-mobile-points-icon.png" }),
        variant("5750+1150 FC POINTS", 790018, { icon: "/images/fc-mobile-points-icon.png" }),
        variant("12000+2400 FC POINTS", 1581024, { icon: "/images/fc-mobile-points-icon.png" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi FC Mobile",
  descriptionIntro:
    "Top up FC Mobile harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore.com. Cara topup FC Mobile via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis points masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const FOOTBALL_MASTER_2: GameDetail = {
  slug: "football-master-2",
  name: "Football Master 2",
  publisher: "GalaSport",
  image: "/games/football-master-2.webp",
  rating: 5.0,
  ratingCount: "210",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("18 FMP", 3647, { icon: null }),
        variant("95 FMP", 18231, { icon: null }),
        variant("191 FMP", 36462, { icon: null }),
        variant("382 FMP", 72924, { icon: null }),
        variant("972 FMP", 182310, { icon: null }),
        variant("1944 FMP", 364619, { icon: null }),
        variant("3888 FMP", 729238, { icon: null }),
        variant("9900 FMP", 1823094, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Football Master 2",
  descriptionIntro: "Top Up FMR Football Master 2 harga paling murah. Cara topup Football Master 2 termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "FMR masuk otomatis ke akun Anda.",
  ],
};

const GARENA_UNDAWN: GameDetail = {
  slug: "garena-undawn",
  name: "Garena Undawn",
  publisher: "Garena",
  image: "/games/garena-undawn.webp",
  rating: 5.0,
  ratingCount: "80",
  idLabel: "ID",
  idTooltip:
    "Untuk menemukan ID Pengguna Anda, klik avatar Anda di pojok kiri atas layar dan klik more . Contoh: 12345678910.",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Special Items (No bind garena)",
      items: [
        variant("Kartu Mingguan (No Garena)", 27762, { icon: null }),
        variant("Kartu Bulanan (No Garena)", 45980, { icon: null }),
        variant("Growth Fund (No Garena)", 92249, { icon: null }),
        variant("Dana Elit (No Garena)", 122323, { icon: null }),
        variant("Ace Fund (No Garena)", 138517, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Tidak bisa untuk akun bind garena",
      items: [
        variant("RC 80 (No Garena)", 14460, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 250 (No Garena)", 43378, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 450 (No Garena)", 72296, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 920 (No Garena)", 143144, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 1850 (No Garena)", 286287, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 2800 (No Garena)", 429431, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 4750 (No Garena)", 715718, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 9600 (No Garena)", 1431435, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 33000 (No Garena)", 4771447, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 66500 (No Garena)", 9542894, { icon: "/images/garena-undawn-rc-icon.webp" }),
      ],
    },
    {
      emoji: "",
      label: "Bisa untuk semua akun",
      items: [
        variant("RC 80", 14462, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 250", 42165, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 450", 72308, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 920", 143652, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 1850", 288265, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 2800", 432880, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 4750", 722110, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 9600", 1445181, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 33000", 4820483, { icon: "/images/garena-undawn-rc-icon.webp" }),
        variant("RC 66500", 9640965, { icon: "/images/garena-undawn-rc-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Garena Undawn",
  descriptionIntro: "Top up RC Garena Undawn harga paling murah, aman, cepat, dan terpercaya. Cara topup RC Garena Undawn :",
  descriptionSteps: [
    "1. Masukkan ID",
    "2. Pilih Nominal",
    "3. Masukkan jumlah",
    "4. Pilih Pembayaran",
    "5. Tulis Kode Promo (jika ada)",
    "6. Masukkan No WhatsApp",
    "7. Klik Order Now & lakukan Pembayaran",
    "8. RC otomatis masuk ke akun game",
    "Note : Akun game harus dalam kondisi login sampai topup selesai",
  ],
};

const GODDESS_OF_VICTORY_NIKKE: GameDetail = {
  slug: "goddess-of-victory-nikke",
  name: "Goddess of Victory: Nikke",
  publisher: "SHIFT UP Corporation",
  image: "/games/goddess-of-victory-nikke.webp",
  rating: 5.0,
  ratingCount: "4",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: ["JP", "NA", "KR", "GLOBAL", "SEA"],
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Special Items",
      items: [variant("Monhtly Pass", 67261, { icon: "/images/nikke-pass-icon.webp" })],
    },
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("6 Gems", 1515, { icon: "/images/nikke-gem-icon.webp" }),
        variant("60 + 1 Gems", 13624, { icon: "/images/nikke-gem-icon.webp" }),
        variant("120 + 3 Gems", 29799, { icon: "/images/nikke-gem-icon.webp" }),
        variant("320 + 10 Gems", 67261, { icon: "/images/nikke-gem-icon.webp" }),
        variant("720 + 120 Gems", 135372, { icon: "/images/nikke-gem-icon.webp" }),
        variant("1500 + 260 Gems", 280109, { icon: "/images/nikke-gem-icon.webp" }),
        variant("2300 + 400 Gems", 407817, { icon: "/images/nikke-gem-icon.webp" }),
        variant("2370 + 420 Gems", 425696, { icon: "/images/nikke-gem-icon.webp" }),
        variant("4200 + 1000 Gems", 765402, { icon: "/images/nikke-gem-icon.webp" }),
        variant("6200 + 1500 Gems", 1105959, { icon: "/images/nikke-gem-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Goddess of Victory: Nikke",
  descriptionIntro:
    "Top up gems Goddess of Victory: Nikke harga paling murah. Cara topup Goddess of Victory: Nikke termurah :",
  descriptionSteps: [
    "Masukkan ID & pilih Server",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Gems otomatis masuk ke akun game",
    "**Proses Manual 1-10 Menit",
  ],
};

const GROWTOPIA: GameDetail = {
  slug: "growtopia",
  name: "Growtopia",
  publisher: "Ubisoft Entertainment",
  image: "/games/growtopia.webp",
  rating: 5.0,
  ratingCount: "62",
  idLabel: "Grow ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("Chest O' Gems", 26208, { icon: null }),
        variant("Gem Fountain", 69122, { icon: null }),
        variant("It's Rainin' Gems", 138381, { icon: null }),
        variant("Royal Glow Pass", 138381, { icon: null }),
        variant("Gem Bounty", 415417, { icon: null }),
        variant("1 Year Subscription Token", 692452, { icon: null }),
        variant("Gem Abundance", 692452, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Growtopia",
  descriptionIntro:
    "Top up gems Growtopia harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore.",
  descriptionSteps: [
    "Cara topup :",
    "1) Masukkan Data Akun",
    "2) Pilih Nominal",
    "3) Tentukan Jumlah Pembelian",
    "4) Pilih Pembayaran",
    "5) Masukkan Kode Promo (jika ada)",
    "6) Isi Detail Kontak",
    "7) Klik Pesan Sekarang dan lakukan Pembayaran",
    "8) Selesai",
  ],
};

const GUNS_OF_GLORY: GameDetail = {
  slug: "guns-of-glory",
  name: "Guns of Glory",
  publisher: "FunPlus International AG",
  image: "/games/guns-of-glory.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("500 Diamonds", 85029, { icon: null }),
        variant("1000 Diamonds", 170342, { icon: null }),
        variant("2000 Diamonds", 341253, { icon: null }),
        variant("5000 Diamonds", 850288, { icon: null }),
        variant("10000 Diamonds", 1706261, { icon: null }),
        variant("20000 Diamonds", 3412522, { icon: null }),
        variant("50000 Diamonds", 8502867, { icon: null }),
        variant("100000 Diamonds", 17062608, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Guns of Glory",
  descriptionIntro:
    "Top up Guns of Glory diamond harga paling murah, aman, cepat, dan terpercaya hanya di Kinzstore. Cara topup Guns of Glory via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis diamond masuk ke akun Anda.",
  descriptionSteps: [
    "Waktu proses 1 detik (setelah pembayaran diterima)",
    "Layanan top up open 24 Jam Non Stop",
    "Bantuan chat WhatsApp open 09.00 - 22.00 WIB",
  ],
};

const HARRY_POTTER_MAGIC_AWAKENED: GameDetail = {
  slug: "harry-potter-magic-awakened",
  name: "Harry Potter Magic Awakened",
  publisher: "NetEase",
  image: "/games/harry-potter-magic-awakened.jpg",
  rating: 5.0,
  ratingCount: "28",
  idLabel: "ID",
  serverLabel: "Pilih Server",
  serverOptions: ["Thunderbird", "不死鳥", "니플러", "Ashwinder", "Sphinx", "Rougarou", "Erumpent", "ユニコーン"],
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("60 Jawels", 16193, { icon: null }),
        variant("300 Jawels", 61315, { icon: null }),
        variant("750 (680+70) Jawels", 123651, { icon: null }),
        variant("1145 (980+165) Jawels", 193640, { icon: null }),
        variant("1550 (1280+270) Jawels", 332960, { icon: null }),
        variant("2360 (1980+380) Jawels", 484766, { icon: null }),
        variant("4060 (3280+780) Jawels", 621359, { icon: null }),
        variant("8480 (6480+2000) Jawels", 1241019, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Harry Potter Magic Awakened",
  descriptionIntro: "Top up Harry Potter Magic Awakened harga paling murah. Cara topup Harry Potter termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Token otomatis masuk ke akun game",
  ],
};

export const GAME_DETAILS_3: Record<string, GameDetail> = {
  [EGGY_PARTY.slug]: EGGY_PARTY,
  [ENSEMBLE_STARS_MUSIC.slug]: ENSEMBLE_STARS_MUSIC,
  [EUDEMONS_ONLINE.slug]: EUDEMONS_ONLINE,
  [FARLIGHT84.slug]: FARLIGHT84,
  [FC_MOBILE.slug]: FC_MOBILE,
  [FOOTBALL_MASTER_2.slug]: FOOTBALL_MASTER_2,
  [GARENA_UNDAWN.slug]: GARENA_UNDAWN,
  [GODDESS_OF_VICTORY_NIKKE.slug]: GODDESS_OF_VICTORY_NIKKE,
  [GROWTOPIA.slug]: GROWTOPIA,
  [GUNS_OF_GLORY.slug]: GUNS_OF_GLORY,
  [HARRY_POTTER_MAGIC_AWAKENED.slug]: HARRY_POTTER_MAGIC_AWAKENED,
};
