import type { GameDetail } from "@/types/game";
import { variant, createPaymentGroups } from "./game-detail-helpers";

const LEAGUE_OF_LEGENDS_PC: GameDetail = {
  slug: "league-of-legends-pc",
  name: "League of Legends : PC",
  publisher: "Riot Games",
  image: "/games/league-of-legends-pc.webp",
  rating: 5.0,
  ratingCount: "34",
  idLabel: "Riot ID",
  idTooltip: "Contoh : bangjeff#123",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Server Indo",
      items: [
        variant("575 RP", 58688, { icon: "/images/lol-rp-icon.webp" }),
        variant("1380 RP", 136939, { icon: "/images/lol-rp-icon.webp" }),
        variant("2800 RP", 273876, { icon: "/images/lol-rp-icon.webp" }),
        variant("4500 RP", 430376, { icon: "/images/lol-rp-icon.webp" }),
        variant("6500 RP", 606439, { icon: "/images/lol-rp-icon.webp" }),
        variant("13500 RP", 1173751, { icon: "/images/lol-rp-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi League of Legends : PC",
  descriptionIntro:
    "Top up RP League of Legends : PC harga paling murah. Cara topup League of Legends : PC termurah :",
  descriptionSteps: [
    "Masukkan Riot ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "RP otomatis masuk ke akun game",
    "**Proses manual max 2 jam",
  ],
};

const LEGACY_FATE_SERVER_OPTIONS: string[] = [
  "Legacy", "Aspect", "Soros", "Eastston", "Spock", "Vertbutter", "Lambence", "Lumen", "Icebell", "Easthall",
  "Myrios", "Vape", "Jinx", "Aelley", "Eastmarsh", "Golem", "Echo", "Fluke", "Plasma", "Icefall",
  "Highash", "Glassford", "Precipe", "Heaf", "Avalan", "Acidosis", "Raymill", "Intra", "Genesis", "Icebush",
  "Glassedge", "Granit", "Saline", "Fate", "Hayden", "Dorhill", "Aeetes", "Scarlet", "Ara", "Alcyoneus",
  "Gavin", "Cassiopeia", "Aquila", "Epeius", "Cygnus", "Fearless", "Bluesage", "Tethys", "Taygetea", "Westerwyn",
  "Arethusa", "Marblemage", "Sao", "Lorfort", "Akheron", "Esteroak", "Herse", "Nepturne", "Eulimene", "Menoetes",
  "Themis",
];

const LEGACY_FATE_SACRED_FEARLESS: GameDetail = {
  slug: "legacy-fate-sacred-fearless",
  name: "Legacy Fate Sacred Fearless",
  publisher: "EYOU TECHNOLOGY PTE LTD",
  image: "/games/legacy-fate-sacred-fearless.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: LEGACY_FATE_SERVER_OPTIONS,
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("70 Token", 15926, { icon: null }),
        variant("130 Token", 32705, { icon: null }),
        variant("330 Token", 79627, { icon: null }),
        variant("750 Token", 159252, { icon: null }),
        variant("990 Token", 238878, { icon: null }),
        variant("1410 Token", 318503, { icon: null }),
        variant("2180 Token", 477754, { icon: null }),
        variant("3610 Token", 796256, { icon: null }),
        variant("7130 Token", 1592511, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Legacy Fate Sacred Fearless",
  descriptionIntro:
    "Top up Token Legacy Fate : Sacred & Farless harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO.",
  descriptionSteps: [
    "Cara topup :",
    "1) Masukkan Data Akun",
    "2) Pilih Nominal",
    "3) Tentukan Jumlah Pembelian",
    "4) Pilih Pembayaran",
    "5) Masukkan Kode Promo (jika ada)",
    "6) Isi Detail Kontak",
    "7) Klik Pesan Sekarang dan lakukan Pembayaran",
    "8) Selesai",
  ],
};

const LIFE_AFTER: GameDetail = {
  slug: "life-after",
  name: "Life After",
  publisher: "NetEase",
  image: "/games/life-after.webp",
  rating: 5.0,
  ratingCount: "18",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: [
    "MiskaTown NA", "SandCastle NA", "MouthSwamp NA", "RedwoodTown NA", "Obelisk NA", "ChaosOutpost NA", "IronStride NA",
    "FallForest AU", "MountSnow AU",
    "NancyCity SEA", "CharlesTown SEA", "SnowHighlands SEA", "Santopany SEA", "LevinCity SEA", "ChaosCity SEA", "TwinIslands SEA", "HopeWall SEA",
    "NewLand NA", "CrystalthornSea NA", "MileStone SEA", "LabyrinthSea SEA",
  ],
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("65 Credits", 16154, { icon: null }),
        variant("330 Credits", 76276, { icon: null }),
        variant("558 Credits", 116658, { icon: null }),
        variant("1108 Credits", 238998, { icon: null }),
        variant("2268 Credits", 478592, { icon: null }),
        variant("3468 Credits", 747799, { icon: null }),
        variant("5768 Credits", 1181522, { icon: null }),
        variant("7768 Credits", 1585333, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Life After",
  descriptionIntro: "Top Up Credits Life After harga paling murah. Cara beli credits LifeAfter termurah :",
  descriptionSteps: [
    "Masukkan ID dan pilih Server",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Credits masuk otomatis ke akun Anda",
  ],
};

const LIFE_MAKEOVER: GameDetail = {
  slug: "life-makeover",
  name: "Life Makeover",
  publisher: "Famous Heart Limited",
  image: "/games/life-makeover.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "User ID",
  idTooltip: "Anda dapat menemukan id pengguna Anda di aplikasi Life Makeover dan mengklik avatar di kanan atas",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Special Item",
      items: [
        variant("Pack Imut", 15642, { icon: null }),
        variant("Member Premium", 78204, { icon: null }),
        variant("Kartu Ganti Nama", 167784, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("60 Kupon", 15642, { icon: null }),
        variant("300 Kupon", 78204, { icon: null }),
        variant("980 Kupon", 241721, { icon: null }),
        variant("1980 Kupon", 483441, { icon: null }),
        variant("3280 Kupon", 796256, { icon: null }),
        variant("6480 Kupon", 1592511, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Life Makeover",
  descriptionIntro:
    "Top up Kupon Life Makeover harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO. Cara topup Life Makeover via ID termurah cukup dengan memasukkan ID dan lakukan pembayaran, secara otomatis kupon masuk ke akun Anda.",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "ES Points otomatis masuk ke akun Anda.",
  ],
};

const LIGHT_OF_THEL_NEW_ERA: GameDetail = {
  slug: "light-of-thel-new-era",
  name: "Light of Thel : New Era",
  publisher: "Ling Ren Game Limited",
  image: "/games/light-of-thel-new-era.webp",
  rating: 5.0,
  ratingCount: "78",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("90 Kristal", 14665, { icon: null }),
        variant("450 Kristal", 70811, { icon: null }),
        variant("630 Kristal", 104979, { icon: null }),
        variant("900 Kristal", 142189, { icon: null }),
        variant("1350 Kristal", 212999, { icon: null }),
        variant("1800 Kristal", 284377, { icon: null }),
        variant("2250 Kristal", 355471, { icon: null }),
        variant("2980 Kristal", 469222, { icon: null }),
        variant("4500 Kristal", 748678, { icon: null }),
        variant("6300 Kristal", 992476, { icon: null }),
        variant("9000 Kristal", 1419042, { icon: null }),
        variant("15000 Kristal", 2129984, { icon: null }),
        variant("32000 Kristal", 4262810, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Light of Thel : New Era",
  descriptionIntro: "Top up crystal Light of Thel : New Era harga paling murah. Cara topup Light of Thel : New Era termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Crystal otomatis masuk ke akun game",
  ],
};

const LORDS_MOBILE: GameDetail = {
  slug: "lords-mobile",
  name: "Lords Mobile",
  publisher: "IGG",
  image: "/games/lords-mobile.webp",
  rating: 5.0,
  ratingCount: "38",
  idLabel: "ID IGG",
  idTooltip: "Untuk menemukan ID IGG Anda, ketuk ikon Roda Gigi di pojok kanan bawah layar, lalu ketuk tombol Akun.",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("395 Diamonds", 73024, { icon: null }),
        variant("785 Diamonds", 146046, { icon: null }),
        variant("1179 Diamonds", 219070, { icon: null }),
        variant("1964 Diamonds", 364253, { icon: null }),
        variant("3928 Diamonds", 730012, { icon: null }),
        variant("7857 Diamonds", 1459915, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Lords Mobile",
  descriptionIntro: "Top up diamond Lords Mobile harga paling murah. Cara topup Lords Mobile termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Diamonds otomatis masuk ke akun game",
  ],
};

const LOVE_AND_DEEPSPACE: GameDetail = {
  slug: "love-and-deepspace",
  name: "Love and Deepspace",
  publisher: "InFold",
  image: "/games/love-and-deepspace.webp",
  rating: 5.0,
  ratingCount: "56",
  idLabel: "AID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Crystals",
      items: [
        variant("60 Crystals", 15200, { icon: null }),
        variant("300 Crystals+30 Diamonds", 76616, { icon: null }),
        variant("450 Crystals+90 Diamonds", 107325, { icon: null }),
        variant("980 Crystals+150 Diamonds", 232965, { icon: null }),
        variant("1980 Crystals+360 Diamonds", 466865, { icon: null }),
        variant("3280 Crystals + 720 Diamonds", 747544, { icon: null }),
        variant("6480 Crystals+1600 Diamonds", 1535213, { icon: null }),
      ],
    },
    {
      emoji: "",
      label: "Pass",
      items: [variant("Aurum Pass (30 Days)", 76616, { icon: null })],
    },
    {
      emoji: "",
      label: "Pack",
      items: [variant("Companionship Pack", 279745, { icon: null })],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Love and Deepspace",
  descriptionIntro:
    "Top up Love and Deepspace harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO.",
  descriptionSteps: [
    "Cara topup :",
    "1) Masukkan Data Akun",
    "2) Pilih Nominal",
    "3) Tentukan Jumlah Pembelian",
    "4) Pilih Pembayaran",
    "5) Masukkan Kode Promo (jika ada)",
    "6) Isi Detail Kontak",
    "7) Klik Pesan Sekarang dan lakukan Pembayaran",
    "8) Selesai",
  ],
};

const MADTALE: GameDetail = {
  slug: "madtale",
  name: "Madtale",
  publisher: "Famous Heart Limited",
  image: "/games/madtale.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("60 Rainbow Diamond", 15642, { icon: "/images/madtale-rainbow-diamond-icon.webp" }),
        variant("300 Rainbow Diamond", 78204, { icon: "/images/madtale-rainbow-diamond-icon.webp" }),
        variant("600 Rainbow Diamond", 142189, { icon: "/images/madtale-rainbow-diamond-icon.webp" }),
        variant("980 Rainbow Diamond", 241721, { icon: "/images/madtale-rainbow-diamond-icon.webp" }),
        variant("1280 Rainbow Diamond", 327034, { icon: "/images/madtale-rainbow-diamond-icon.webp" }),
        variant("1980 Rainbow Diamond", 483441, { icon: "/images/madtale-rainbow-diamond-icon.webp" }),
        variant("3280 Rainbow Diamond", 796256, { icon: "/images/madtale-rainbow-diamond-icon.webp" }),
        variant("6480 Rainbow Diamond", 1592511, { icon: "/images/madtale-rainbow-diamond-icon.webp" }),
        variant("12960 Rainbow Diamond", 3128145, { icon: "/images/madtale-rainbow-diamond-icon.webp" }),
        variant("19440 Rainbow Diamond", 4692218, { icon: "/images/madtale-rainbow-diamond-icon.webp" }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Madtale",
  descriptionIntro: "Top up Madtale harga paling murah. Cara topup Madtale termurah :",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Masukkan jumlah",
    "Pilih Pembayaran",
    "Tulis Kode Promo (jika ada)",
    "Masukkan No WhatsApp",
    "Klik Order Now & lakukan Pembayaran",
    "Rainbow Diamond otomatis masuk ke akun game",
  ],
};

const MAPLESTORY_R_EVOLUTION_SERVER_OPTIONS: string[] = [
  "Maple Village", "Maple Island", "Grove", "Henesys", "Aqua Road", "Star Tower", "Sakura City", "Ailinie", "Golden Coast", "Mushroom City",
  "Six Roads", "Tale Village", "Ludus", "Time Tower", "Minar Forest", "Leafre", "Mirror World", "Aswan", "Obelisk", "Herb Town",
  "Elderstein", "Mysterious Island", "Kleis", "Erodin", "Palethan", "Temple of Gods", "Fox Valley", "Tulun City", "Asulon", "Belda",
  "Cloud Valley", "Yaxus", "Mysterious River", "Inverted City", "Amaze Island", "Chirp Island", "Tower of Babel", "Dream City", "Morass", "Serass",
  "Snail", "Blue Snail", "Red Snail", "Baby Mushroom", "Slime", "Bubbling", "Fairy", "Green Mushroom", "Orange Mushroom", "Blue Mushroom",
  "Stone Golem", "Wild Boar", "Iron Hog", "Fire Boar", "Unicorn", "Eliza", "Crimson Balrog", "Mano", "Primitive Boar", "Master Death Teddy",
  "Pixie", "Stumpy", "Axe Stump", "Ghost Stump", "Jr. Wraith", "Wraith", "Shade", "Spirit Viking", "Seruf", "Seacle",
  "Cico", "Krip", "Bubble Fish", "Goby", "Squid", "Bone Fish", "Red Dragon", "Blue Dragon", "Black Dragon", "Skeleton Dragon",
  "Perion", "Kerning City", "Ellinia", "Fairy Academy", "Irene Forest", "Big Whale", "Gold Beach", "Fantasy Village", "Defense Headquarters", "Lena Strait",
  "Verne Mines", "Tara Forest", "Rock Behemoth", "Carruthers", "Cave of Life", "El Nath", "Lion Castle", "Orbis", "Snow Canyon", "Beritas",
  "Undersea Tower", "Ariant", "Ariante", "Magatia", "Mu Lung", "Golden Temple", "Temple of Time", "Gate to the Past", "Gate to the Present", "Gate to the Future",
  "Teru Efi", "Helisimus", "Tyrant Castle", "Miu Miu", "Barbarian End", "Sertiu", "Mysterious Forest", "Arcana", "Sea of Genesis", "Espera",
  "Slime King", "Ephenia", "Horntail", "Mushmom", "Star Pixie", "Lunar Pixie", "Luster Pixie", "Cellion", "Lioner", "Grupin",
  "Evil Eye", "Curse Eye", "Cold Eye", "Surgeon Eye", "Gryffindor", "Zakum", "Seagull Slime", "Flying Fish Slime", "Starfish Slime", "Seashell Slime",
  "Lucida", "Desert Giant", "Ear Plug Plead", "Scarf Plead", "Kiyo", "Scorpion", "Sand Dwarf", "King Block Golem", "Planey", "Helly",
  "Propelly", "Toy Trojan", "Ratz", "Drumming Bunny", "Brown Teddy", "Panda Teddy", "Gigantic Spirit Viking", "Dual Ghost Pirate", "Ghost Pirate", "Phantom Witch",
  "Guard Robot", "Royal Fairy", "Dyle", "Skeleton Commander", "Nependeath", "Ore Muncher", "Flower Fish", "Bellamoa", "Krappy", "Bombing Fish House",
  "King Bloctopus", "Blue Bubble Fish", "Soul Teddy", "Death Teddy", "Captain Darkgoo", "Coconut Slime", "tPalm Tree Slime", "Emerald Clam Slime", "Violet Clam Slime", "Red Tube Slime",
  "Blue Tube Slime", "Risell Squid", "Jr. Cellion", "Jr. Lioner", "Jr. Grupin", "Destroyer Creature", "Chaos Creature", "Fear Gazer", "Fear Raider", "Blue Spirit Mage",
  "Black Spirit Mage", "Lizardfolk Chief", "Red Kentaurus", "Blue Kentaurus", "Black Kentaurus", "Green Cornian", "Dark Cornian", "Zombie Mushmom", "Dark Stone Golem", "Mixed Golem",
  "Light Dance", "Power of Torrent", "Leaf Lunge", "Blazing Slash", "Aura Eruption", "Ultimate Turbulence", "Shattered Void", "Judgment Blade", "Cyclone Assault", "Lucky Dice",
  "Concentrated Gunfire", "Magnetic Anchor", "Hell Burst Bomb", "Holographic Laser", "Fury of Phoenix", "Mist Burst", "Blazing Fire", "Doomsday Fiery", "Double Strike", "Storm Arrow",
  "Lightspeed Crossbow", "Fatal Shot", "Phantom of Arrow", "Flame Quiver", "Shower Arrow", "Showdown Time", "Total Vanish", "Scarlet Hunt", "Ice Point", "Triumph Horn",
  "Firm Belief", "Heart of Rage", "Soul of Sanctuary", "Magic Control", "Full Attack", "Summon of Flame", "Inescapable Snare", "Apex Strike", "Poison Orb", "Surprise Attack",
  "Zakum Helmet", "Phantom of Faith", "Phantom of Sky", "Golden Wings", "Black Star Sand", "Graceful Blossom", "Angels Bow", "Feather Alloy", "Lilynouch", "Crystal Blue",
  "Wings of Victory", "Moon Shadow", "Blue Laser", "Blue Vortex", "Frog Green Leaf", "Summer Pond", "Ice-breaking", "Merciless Ice", "Azure Wings", "Dazzling Purple",
  "Flowing Gold", "Cycle of Life", "Frost Odin", "Flowing Magic", "Suda Lion Heart", "Novice Wanderer", "Winter Storm", "Winter Ghost", "Winter Chill", "Magic of Alchemy",
  "7001", "7002", "7112", "7103", "Overwhelming Universe", "Controlling Arena", "Bathed in Glory", "Dusk Apocalypse", "Prosperous Bull", "Auspicious Bull",
  "Bull is Luck", "7101", "7001", "测试7111", "测试7113", "测试7114", "测试7115", "测试7116", "测试7117", "测试7118",
  "测试7121", "测试7131", "测试7132", "测试7133", "测试7134", "测试7135", "测试7136", "测试7137", "测试7138", "测试7141",
  "测试7142", "测试7143", "测试7144", "测试7145", "测试7146", "测试7147", "测试7148", "Maple Belief", "测试7151", "测试7152",
  "测试7163", "测试7154", "测试7155", "测试7156", "测试7157", "测试7158", "测试7161", "测试7162", "测试7163", "测试7164",
  "测试7165", "测试7166", "测试7167", "测试7168",
];

const MAPLESTORY_R_EVOLUTION: GameDetail = {
  slug: "maplestory-r-evolution",
  name: "Maplestory R Evolution",
  publisher: "Rastar Games HK",
  image: "/games/maplestory-r-evolution.webp",
  rating: 0,
  ratingCount: "0",
  idLabel: "ID",
  serverLabel: "Server",
  serverOptions: MAPLESTORY_R_EVOLUTION_SERVER_OPTIONS,
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Topup Instant",
      items: [
        variant("11 Colored Diamonds", 196523, { icon: null }),
        variant("22 Colored Diamonds", 393045, { icon: null }),
        variant("45 Colored Diamonds R3", 786090, { icon: null }),
        variant("67 Colored Diamonds R4", 1179134, { icon: null }),
        variant("112 Colored Diamonds R5", 1965224, { icon: null }),
        variant("180 Colored Diamonds R6", 3144356, { icon: null }),
        variant("224 Colored Diamonds R7", 3930446, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Maplestory R Evolution",
  descriptionIntro:
    "Top up colored diamonds MapleStory R : Evolution harga paling murah, aman, cepat, dan terpercaya hanya di ALIGO.",
  descriptionSteps: [
    "Cara topup :",
    "1) Masukkan Data Akun",
    "2) Pilih Nominal",
    "3) Tentukan Jumlah Pembelian",
    "4) Pilih Pembayaran",
    "5) Masukkan Kode Promo (jika ada)",
    "6) Isi Detail Kontak",
    "7) Klik Pesan Sekarang dan lakukan Pembayaran",
    "8) Selesai",
  ],
};

const MARVEL_DUEL: GameDetail = {
  slug: "marvel-duel",
  name: "Marvel Duel",
  publisher: "NetEase",
  image: "/games/marvel-duel.webp",
  rating: 5.0,
  ratingCount: "28",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up Instant",
      items: [
        variant("6 Stardust", 17319, { icon: null }),
        variant("30 Stardust + 10 Iso Gems", 88268, { icon: null }),
        variant("180 Stardust + 200 Iso Gems", 395290, { icon: null }),
        variant("300 Stardust + 400 Iso Gems", 886450, { icon: null }),
        variant("600 Stardust + 860 Iso Gems", 1773319, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi Marvel Duel",
  descriptionIntro:
    "Top up Stardust & ISO Gems Marvel Duel harga paling murah, aman, cepat, dan terpercaya. Cara topup Stardust & ISO Gems Marvel Duel:",
  descriptionSteps: [
    "1. Masukkan ID",
    "2. Pilih Nominal",
    "3. Masukkan jumlah",
    "4. Pilih Pembayaran",
    "5. Tulis Kode Promo (jika ada)",
    "6. Masukkan No WhatsApp",
    "7. Klik Order Now & lakukan Pembayaran",
    "8. Stardust & ISO Gems otomatis masuk ke akun game",
  ],
};

const MARVEL_SUPER_WAR: GameDetail = {
  slug: "marvel-super-war",
  name: "MARVEL Super War",
  publisher: "NetEase",
  image: "/games/marvel-super-war.webp",
  rating: 5.0,
  ratingCount: "4",
  idLabel: "ID",
  idNote: "Pastikan kamu mengisi data akun dengan benar.",
  categories: [
    {
      emoji: "",
      label: "Top Up",
      items: [
        variant("55 Star Credits", 11498, { icon: null }),
        variant("275 Star Credits", 58665, { icon: null }),
        variant("565 Star Credits", 117624, { icon: null }),
        variant("1155 Star Credits", 235543, { icon: null }),
        variant("1765 Star Credits", 382939, { icon: null }),
        variant("2950 Star Credits", 589295, { icon: null }),
        variant("6000 Star Credits", 1178884, { icon: null }),
      ],
    },
  ],
  paymentGroups: createPaymentGroups(),
  descriptionTitle: "Deskripsi MARVEL Super War",
  descriptionIntro: "Top Up Star Credits MARVEL Super War",
  descriptionSteps: [
    "Masukkan ID",
    "Pilih Nominal",
    "Pilih Pembayaran",
    "Klik Order Now & lakukan Pembayaran",
    "Star Credits masuk otomatis ke akun Anda.",
  ],
};

export const GAME_DETAILS_5: Record<string, GameDetail> = {
  [LEAGUE_OF_LEGENDS_PC.slug]: LEAGUE_OF_LEGENDS_PC,
  [LEGACY_FATE_SACRED_FEARLESS.slug]: LEGACY_FATE_SACRED_FEARLESS,
  [LIFE_AFTER.slug]: LIFE_AFTER,
  [LIFE_MAKEOVER.slug]: LIFE_MAKEOVER,
  [LIGHT_OF_THEL_NEW_ERA.slug]: LIGHT_OF_THEL_NEW_ERA,
  [LORDS_MOBILE.slug]: LORDS_MOBILE,
  [LOVE_AND_DEEPSPACE.slug]: LOVE_AND_DEEPSPACE,
  [MADTALE.slug]: MADTALE,
  [MAPLESTORY_R_EVOLUTION.slug]: MAPLESTORY_R_EVOLUTION,
  [MARVEL_DUEL.slug]: MARVEL_DUEL,
  [MARVEL_SUPER_WAR.slug]: MARVEL_SUPER_WAR,
};
